### PR TITLE
Add detection of Altivec for AmigaOS4

### PR DESCRIPTION
**Pull request by chris-y**
This patch adds detection of Altivec on the AmigaOS 4 (PowerPC) operating system.

### CODE REVIEW

**Comment by dcommander** [comment]
Please combine these into a single commit with the following commit message:

``Detect AltiVec support on AmigaOS 4``

then I will merge it.  Thanks.  Also please confirm that 'make test' passes on that platform (it is our policy not to include platform-specific code unless libjpeg-turbo fully functions on that platform.)

Amazing that AmigaOS is still around.  I had a 68030-based Amiga 2000 back in the day.

**Comment by dcommander** [comment]
Never mind.  I just noticed that GitHub now includes a "Squash and Merge" feature.  :)  It has been merged.  Thanks!

**Comment by chris-y** [comment]
Thanks!  `make test` gives me "GREAT SUCCESS!", which I guess is good.  However, it then goes on to complain:

```
cp ./testimages/testorig.ppm testout_tile.ppm
./tjbench testout_tile.ppm 95 -rgb -quiet -tile -benchtime 0.01 >/dev/null 2>&1
for i in 8 16 32 64 128; do \
		md5/md5cmp 89d3ca21213d9d864b50b4e4e7de4ca6 testout_tile_GRAY_Q95_$i\x$i.ppm; \
	done
testout_tile_GRAY_Q95_8x8.ppm: FAILED.  Checksum is efd042424eada1a3f486c4d5e7f69676
testout_tile_GRAY_Q95_16x16.ppm: FAILED.  Checksum is efd042424eada1a3f486c4d5e7f69676
testout_tile_GRAY_Q95_32x32.ppm: FAILED.  Checksum is efd042424eada1a3f486c4d5e7f69676
testout_tile_GRAY_Q95_64x64.ppm: FAILED.  Checksum is efd042424eada1a3f486c4d5e7f69676
testout_tile_GRAY_Q95_128x128.ppm: FAILED.  Checksum is efd042424eada1a3f486c4d5e7f69676
```

I think this might actually be a problem with your md5cmp when built for PPC, as md5sum gives the expected answer:
```
md5sum testout_tile_GRAY_Q95_8x8.ppm 
89d3ca21213d9d864b50b4e4e7de4ca6  testout_tile_GRAY_Q95_8x8.ppm
```

**Comment by dcommander** [comment]
Weird.  It works properly on PowerPC Linux and OS X (building with the old OS X 10.4 universal SDK, which was the last to support PPC, and running under Rosetta on OS X 10.6.)

`make test` will report "GREAT SUCCESS" after each stage, so apparently the first stage (`make tjquicktest`) succeeded, but the second stage (`make tjbittest`) failed, and the third stage (`make bittest`) was not run.

If you can figure out what's wrong, please submit another PR.  There's very little else I could do, unless this is somehow reproducible on another platform.

**Pull request merged**
