### PR TITLE
Implement MSA optimization codes for MIPS platform on dev branch

### PR DESCRIPTION
**Pull request by hbi01**
Hello,
I have finished the MSA-optimized codes for MIPS platform on libjpeg-turbo:
1. A month ago, I submitted a pull request for MSA implementation on master branch and you give me lots of comments, this time I updated these codes as your comments and submitted it again on dev branch. Please help to review it, thank you very much.
2. I have run the checkstyle script from https://github.com/libjpeg-turbo/checkstyle and all MSA-optimized files can pass this test.
3. About performance test, I attach the file - libjpgturbo-mips-performance-report-1core_0926.xlsx which includes the comparable results between libjpeg v6b and libjpeg-turbo dev with MSA code. I run tjbench on Elise board(based MIPS32R5) and get it. On the other hand I also run tjunittest on it all test cases can be passed.

If you have any questions or comments please feel free to let me know, we will discuss them further. We hope you help us to upstream these codes to the github in the near future. Thank you very much.
[libjpgturbo-mips-performance-report-1core_0926.xlsx](https://github.com/libjpeg-turbo/libjpeg-turbo/files/3661092/libjpgturbo-mips-performance-report-1core_0926.xlsx)

### CODE REVIEW

**Comment by dcommander** [comment]
OK, then the next steps will be, as stated in #373, for your organization to secure 30 hours of funding for my labor to review, test, and integrate the code, as well as provide temporary access to a test machine with stable performance, so I can use that for benchmarking.  I am happy to send a formal estimate for this work.

**Comment by hbi01** [comment]
Hi DRC,
I have informed our leader (rfuhler@wavecomp.com) about this 30 hours funding issue. He will deal with it in the next days. If there are some new progresses I will let you know. Thank you very much.

**Comment by dcommander** [comment]
I have not heard anything further regarding integration funding.  The window for getting this feature into libjpeg-turbo 2.1 is closing quickly.

**Comment by wzssyqa** [comment]
@dcommander Bi leaves from Wave. I will track on it.

**Comment by dcommander** [comment]
The window for getting this into libjpeg-turbo 2.1 is unfortunately lost.  Please contact me if you still wish to pursue this for a future libjpeg-turbo release.

**Comment by dcommander** [comment]
Closed due to lack of follow-through from OP regarding funding for my labor to integrate the MSA SIMD extensions, as well as access to a test platform.  Please contact me if you still want to pursue this project for libjpeg-turbo 2.2.

**Pull request closed without merging**
