### PR TITLE
Clarify average implementation for flatten

### PR DESCRIPTION
**Pull request by malaterre**
The function `do_flatten` is implemented using bitshift instead of
division, so the average is rounded up for negative values:

  average = (dc_left_value + dc_right_value) >> 1;

### CODE REVIEW

**Comment by dcommander** [comment]
That feature and its associated documentation were borrowed from libjpeg v9a and v9d.  Given that most end users will not have a deep understanding of the algorithms involved, I feel that this comment may further confuse the issue, since those users will not understand what "negatives" are.  Is there a common name for this type of averaging, such as "bitwise average", that would convey the necessary concept to advanced users without confusing typical users?

**Comment by malaterre** [comment]
@dcommander Thanks for your review. IMHO all users of `jpegtran` have a pretty deep understanding of what `average` stands for. AFAIK they should also understand what `round up` means.

In any case reviewing the article:

* https://en.wikipedia.org/wiki/Arithmetic_shift#Non-equivalence_of_arithmetic_right_shift_and_division

Does not give a name for pseudo-averaging using bitshit, they even pretty clearly states that those operations should not be confused. Note 7, goes even further claiming that "Arithmetic Shifting Considered Harmful".

I'll be bold and state that this is in fact a bug. Clearly DC value can be negatives. Let me check with upstream and report back here (hopefully).

**Comment by dcommander** [comment]
Yes, if this causes inconsistent behavior between certain types of blocks, then it is probably better to correct the algorithm rather than explain it away.

**Comment by dcommander** [comment]
Also, isn't shifting a negative number technically undefined behavior?  If UBSan triggers on this, then it should definitely be considered a bug.

**Comment by malaterre** [comment]
AFAIK, the entire JPEG specification rely on 2-complement(*).

(*) https://stackoverflow.com/questions/40508958/shifting-a-negative-signed-value-is-undefined

**Comment by dcommander** [comment]
My mistake.  Only left shifting a negative number is undefined.  Right shifting a negative number is OK but produces round-down behavior, as you observed.

**Comment by malaterre** [comment]
Average is exactly defined in mathematical terms, but can be implemented only as an approximation of it. For instance:

`*outptr++ = (JSAMPLE)((inptr[0] + inptr[1] + bias) >> 1);
`

reference:

* https://github.com/libjpeg-turbo/libjpeg-turbo/blob/main/jcsample.c#L240

**Comment by dcommander** [comment]
I don't understand why you closed this, nor do I understand your comment above.  Are you still going to pursue the matter with the IJG?

**Comment by malaterre** [comment]
@dcommander Yes, I did exchanged quite a bit with Guido Vollbeding. The last comment is extracted from his last email. Basically the notion of `average` is perfectly clear in the documentation. Since IJG is not going to update the documentation, there is little interest in having a (pedantic) documentation patch here to repeat the above:

* https://github.com/libjpeg-turbo/libjpeg-turbo/pull/561#issuecomment-976250592

**Comment by dcommander** [comment]
I am still unclear.  Why are you saying that the notion of average is perfectly clear in the documentation when you posted this PR in order to clarify it?  What changed your mind?

**Comment by dcommander** [comment]
Here is a roll-up of my understanding of this issue, based on offline conversations and my own research:

DCT coefficients can be negative only because JPEG requires a sample range of -128 to 127 (or -2048 to 2047 for 12-bit JPEG.)  Referring to 4.1.4 in the spec, "This zero-shift reduces the internal precision requirements in the DCT calculations."  Thus, there is no special meaning to negative DCT coefficients, so rounding toward zero would definitely be wrong.  An argument could be made that the computation should round up or down for every other block, to avoid biasing toward negative infinity, but such would produce no visible difference for the user.  The entire purpose of the flatten feature is to wipe the image content from specific DCT blocks using a single color that is contextually appropriate for the blocks (rather than using neutral gray), so there doesn't seem to be much point to splitting hairs regarding the accuracy of a feature that is basically designed to eliminate all accuracy from an image region.

**Pull request closed without merging**
