### PR TITLE
Fix compilation errors under linux enviroment

### PR DESCRIPTION
**Pull request by MatusKysel**
Hi, I have tried to use your lib on linux with cmake and it was not working, so I have added few changes

### CODE REVIEW

**Comment by dcommander** [comment]
I have received multiple pull requests, issue submissions, and (back when we were on SourceForge) tracker items asking for Un\*x support in the CMake build system, so let me lay out the situation once and for all, so I can at least refer people to this response the next time I get one of these requests.  The CMake build system supports only Windows, and the Autotools build system supports only Un*x.  This is by design and is well documented in the build instructions (BUILDING.txt in libjpeg-turbo 1.4.x, or BUILDING.md in the evolving 1.5.x code.)  There are several reasons for this design:

- CMake is a much more natural fit for Windows environments, because:
  - Autotools is extremely slow on Windows.
  - Installing Autotools on Windows is not very easy (you have to install and configure a Un*x-like environment such as MSYS or Cygwin.)
  - CMake allows for generating Visual Studio project files, which most Windows developers prefer over command-line scripts.

- Autotools is a more natural fit for Un*x environments, because:
  - Cross-compilation is more straightforward with it (and cross-compilation is important, because that's how we generate libjpeg-turbo binaries for mobile platforms.)
  - libjpeg-turbo is a core system library on many platforms, and at least in the GNU world, there tends to be an expectation that core system libraries will be built with autotools.
  - Not all Un*x-like O/S's have CMake.
  - More developers on that platform are familiar with editing autotools scripts than CMake scripts.

- I categorically will not support multiple build systems on one platform.

Personally, I prefer CMake, but it isn't as easy as waving my hand and switching to it.  I would first have to make sure that the major O/S distributors are OK with that change.  If one of them says no, then it's dead.  I would then need to port in all of the packaging system and support for various non-x86 assemblers and a variety of other things that exist in the Un\*x build system but have never existed in the Windows build system (because, for instance, there is no need for building Windows code on anything but ARM or x86 processors.)  It took many many hours (mostly pro bono) to get the build systems working as well as they work now.  A lot of those hours of testing will have to be repeated in order for me to be confident that CMake can replace everything that the autotools build system currently does.

The problem is that I don't get paid for my work on this project unless I'm working on a specific contract, which usually entails developing a specific feature for a specific company.  Thus, I very much need to keep the general maintenance of the code to a minimum.  This is why I won't support two build systems on the same platform, and that will remain the case as long as the funding situation for libjpeg-turbo remains as it is.  If someone steps forward with a General Fund that I can pull from, a fund that would allow me to take on these kinds of forward-looking projects while still paying my rent, then my attitude will change greatly.  But otherwise, I have absolutely nothing to gain by extending the CMake build system.  I would only be creating more unpaid work for myself.  If someone in the community was willing to put forth the (probably extensive) effort to completely overhaul the build system the right way, that would be great, but history doesn't suggest that that will ever happen.  No one in the community knows this code like I do.  The community has on several occasions tried to extend the CMake build system, but those patches didn't get it right and would have required more effort to fix than to completely rewrite from scratch.  And even if I was able to use a code contribution from the community, I'd still have to make sure that the major O/S distributors are OK with introducing a CMake dependency.

I will support Un\*x fully under CMake or not at all.  And supporting it fully doesn't mean just making things build on one specific system.  Our CMake build system doesn't pretend to work on Un\*x.  This is clearly documented in the build instructions, and if you try to do it, the build system notifies you that CMake is only supported on Windows.  That's the way it will remain until/unless someone is willing to go to the (extensive) trouble to support Un\*x the correct way under CMake or unless they're willing to pay me to do that work.

**Comment by dcommander** [comment]
See also:
https://github.com/libjpeg-turbo/libjpeg-turbo/issues/21

**Comment by dcommander** [comment]
Cross-platform CMake build system is now available in dev.  Please test.

**Comment by MatusKysel** [comment]
https://github.com/libjpeg-turbo/libjpeg-turbo/pull/122 I have added some fixes

**Pull request closed without merging**
