### PR TITLE
x86 SIMD: Add endbr32/endbr64 instructions

### PR DESCRIPTION
**Pull request by nforro**
Allow for indirect branch tracking with [Intel CET (Control-Flow Enforcement Technology)](https://software.intel.com/sites/default/files/managed/4d/2a/control-flow-enforcement-technology-preview.pdf), by making all exported routines a possible target for an indirect jump.

### CODE REVIEW

**Comment by dcommander** [comment]
Please provide the following information about this patch:
1. What exactly does it do?
2. How can I see the benefits of it for myself?
3. How backward compatible is it?

**Comment by dcommander** [comment]
@nforro if you do not provide the information requested, there is no way I can accept this patch.  Please answer my questions above.

**Comment by nforro** [comment]
> What exactly does it do?

It adds new instructions that are expected to follow every indirect branch in a CET-enabled program.
The purpose of that is to help defend against return-oriented programming.

> How can I see the benefits of it for myself?

I'm afraid there is no way currently. You would need CET-enabled CPU (there are none so far), CET-enabled OS/kernel (the support hasn't been merged to Linux yet) and an CET-capable application that is using libjpeg-turbo.

> How backward compatible is it?

It's fully backward compatible, the new instructions are NOP on older CPUs.

**Comment by dcommander** [comment]
Deferred until a way exists for me to test this.  I cannot check in any code that I cannot personally test, because that code would be impossible to maintain, but suffice it to say that I am skeptical of the claim that this is "fully backward compatible."  I strongly suspect that it requires a particular minimum version of NASM or YASM, for instance, which would need to be documented-- further reason why I need to be able to test it for myself.

**Comment by loqs** [comment]
@nforro should support for the .note.gnu.property section be added before indirect branch tracking support rather than relying on the builder adding ``` -Wl,-z,ibt -Wl,-z,shstk``` to LDFLAGS [1]?  As both features of CET;  shadow stack and indirect branch tracking require it.
@dcommander shadow stack support for user-space is included in linux 5.6 https://github.com/torvalds/linux/commit/df57721f9a63e8a1fb9b9b2e70de4aa4c7e0cd2e assuming it is not removed before the 5.6 release I would expect compatible glibc support to be added after that release.  I believe there have been no recent patch series of indirect branch tracking for user-space proposed for the linux kernel.    

[1]: https://src.fedoraproject.org/rpms/libjpeg-turbo/blob/10c0e22bf9180b133d8fd7f503b06a1d04aff0db/f/libjpeg-turbo.spec#_77

**Comment by dcommander** [comment]
@loqs OK.  Then the issue would be the fact that I have no access to a CPU that supports the instructions in question, so I have no way to independently test this PR.  The best I could do at the moment is to ensure that it does no harm on non-CET-enabled CPUs and rely on someone else in the community to test it on a CET-enabled CPU and verify that it solves the problem as intended.

**Comment by loqs** [comment]
What if CET support was only enabled if it was being used to compile the C code? If the C code is not being built with CET support there is no benefit to building the ASM with it. When indirect branch tracking is not enabled _endbr32/_endbr64 would expand to nothing. When CET support (indirect branch tracking and user space shadow stack) is not enabled .note.gnu.property section would not be included.
If jsimdcfg.inc was still auto generated at build time then it would be trivial to add CET detection.
One possible way to add it using check_c_source_compiles :
```patch
   set(CMAKE_ASM_NASM_FLAGS "${CMAKE_ASM_NASM_FLAGS} -DPIC")
 endif()
 
+check_c_source_compiles("
+  #if (__CET__ & 1) != 1
+  #error
+  #endif
+  int main(void) { return 0; }" HAVE_IBT)
+
+check_c_source_compiles("
+  #if (__CET__ & 2) != 2
+  #error
+  #endif
+  int main(void) { return 0; }" HAVE_SHSTK)
+
+if(HAVE_IBT AND HAVE_SHSTK)
+  set(CET "3")
+elseif(NOT HAVE_IBT AND HAVE_SHSTK)
+  set(CET "2")
+elseif(HAVE_IBT AND NOT HAVE_SHSTK)
+  set(CET "1")
+endif()
+
+if(CET)
+  set(CMAKE_ASM_NASM_FLAGS "${CMAKE_ASM_NASM_FLAGS} -D__CET__=${CET}")
+endif()
+
 string(TOUPPER ${CMAKE_BUILD_TYPE} CMAKE_BUILD_TYPE_UC)
 set(EFFECTIVE_ASM_NASM_FLAGS "${CMAKE_ASM_NASM_FLAGS} ${CMAKE_ASM_NASM_FLAGS_${CMAKE_BUILD_TYPE_UC}}")
 message(STATUS "CMAKE_ASM_NASM_FLAGS = ${EFFECTIVE_ASM_NASM_FLAGS}")
```
Are i486 and i566 supported? As https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98667 indicates endbr32 is not supported on those architectures.

With respect to .note.gnu.property could a possible implementation could be based on https://github.com/intel/isa-l/commit/57846f414f3b28aa9e6b1c115959175b58ad23a0?  .note.gnu.property was added to YASM in https://github.com/netwide-assembler/nasm/commit/dc5939b4960e169e19c536e5503ec4487cff550d. .note.gnu.property was added to NASM in https://github.com/yasm/yasm/commit/0799f381d513e18f404654047fa1b412084968c8 (no release since).
@hjl-tools any interest in adding this?

I can test user space shadow stack support on linux x86_64 which now has glibc and kernel support.  There is still no kernel support for indirect branch tracking.  I also lack the hardware to test that.

**Comment by dcommander** [comment]
> What if CET support was only enabled if it was being used to compile the C code? If the C code is not being built with CET support there is no benefit to building the ASM with it.

That's a great idea, since it will allow people to test the feature without affecting the default build of libjpeg-turbo.  I will look into it.  Note also that #732 would obviate this, but that's a longer-term project with a much larger scope.

> Are i486 and i566 supported? As https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98667 indicates endbr32 is not supported on those architectures.

OK, so does that mean that the i386 SIMD extensions do not need endbr32 instructions?

> With respect to .note.gnu.property could a possible implementation could be based on [intel/isa-l@57846f4](https://github.com/intel/isa-l/commit/57846f414f3b28aa9e6b1c115959175b58ad23a0)? .note.gnu.property was added to YASM in [netwide-assembler/nasm@dc5939b](https://github.com/netwide-assembler/nasm/commit/dc5939b4960e169e19c536e5503ec4487cff550d). .note.gnu.property was added to NASM in [yasm/yasm@0799f38](https://github.com/yasm/yasm/commit/0799f381d513e18f404654047fa1b412084968c8) (no release since). @hjl-tools any interest in adding this?

I don't really understand what .note.gnu.property does or how it ties into this feature.

**Comment by loqs** [comment]
> > What if CET support was only enabled if it was being used to compile the C code? If the C code is not being built with CET support there is no benefit to building the ASM with it.
> 
> That's a great idea, since it will allow people to test the feature without affecting the default build of libjpeg-turbo. I will look into it. Note also that #732 would obviate this, but that's a longer-term project with a much larger scope.
> 
> > Are i486 and i566 supported? As https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98667 indicates endbr32 is not supported on those architectures.
> 
> OK, so does that mean that the i386 SIMD extensions do not need endbr32 instructions?
No they need the instructions its just that at least i686 is required for endbr32 to be treated as a NOP on unsupported CPU's
```
$ touch a.c
$ gcc -m32 -march=i386 -fcf-protection=branch a.c
cc1: error: ‘-fcf-protection’ is not compatible with this target
```
Same for i486 and i586. i686 is the first -march supporting it as that is the first with CMOV. If the compiler is already guarding against the bad combination then if the ASM code's CET support is tied to that of of the  C code it will prevent this being an issue. I would suggest continuing to defer adding endbr32/enbr64 support until there is a platform that supports it and can be tested against.
> 
> I don't really understand what .note.gnu.property does or how it ties into this feature.

https://raw.githubusercontent.com/wiki/hjl-tools/linux-abi/linux-abi-draft.pdf#subsection.2.1.5 if the .note.gnu.property of all object files for a target contain GNU_PROPERTY_X86_FEATURE_1_SHSTK the linker will add that to targets .note.gnu.property.  glibc checks the .note.gnu.property of an executable and all libraries linked to it for GNU_PROPERTY_X86_FEATURE_1_SHSTK to check for user space shadow stack support.

**Comment by dcommander** [comment]
@loqs You had me, then you lost me.  In your comment yesterday, you seemed to be advocating for the inclusion of this patch (with modifications to ensure that it is only activated if the C code is built with CET support.)  Now you seem to be advocating that we wait until platform support is available.

**Comment by loqs** [comment]
As no change beyond the note is required for shadow stack support. I would suggest the following:
1. Detect use of CET in C code and pass that to the ASM.
2. In the ASM add  .note.gnu.property supporting GNU_PROPERTY_X86_FEATURE_1_SHSTK for ELF 64 if CET is in use.

That would support user space shadow stack on linux 64. An alternative approach would be to detect the C code is using CET and the platform is linux 64 in cmake and add `-z,shstk` to the link flags instructing the linker to add  .note.gnu.property supporting GNU_PROPERTY_X86_FEATURE_1_SHSTK even though the object files are not marked as supporting it. That avoids making any changes to the ASM.

I would defer any further work until there is a platform that supports/requires it.  When there is a platform that supports indirect branch tracking this pull can be adjusted and merged.

**Comment by dcommander** [comment]
> As no change beyond the note is required for shadow stack support. I would suggest the following:
> 
> 1. Detect use of CET in C code and pass that to the ASM.
> 
> 2. In the ASM add  .note.gnu.property supporting GNU_PROPERTY_X86_FEATURE_1_SHSTK for ELF 64 if CET is in use.
> 
> 
> 
> That would support user space shadow stack on linux 64. An alternative approach would be to detect the C code is using CET and the platform is linux 64 in cmake and add `-z,shstk` to the link flags instructing the linker to add  .note.gnu.property supporting GNU_PROPERTY_X86_FEATURE_1_SHSTK even though the object files are not marked as supporting it. That avoids making any changes to the ASM.
> 
> 
> 
> I would defer any further work until there is a platform that supports/requires it.  When there is a platform that supports indirect branch tracking this pull can be adjusted and merged.

So, just to be clear, you are proposing that we add shadow stack support now and defer indirect branch tracking support until later, when a platform supports it? I am fine with that, but if endbr32/endbr64 are only useful for indirect branch tracking, then what other changes would be necessary in the assembly code? I thought the point of your suggestion above was to define a NASM macro if the build system detected that the C code was being compiled with CET support, but it doesn't seem necessary to do that just to enable shadow stack support.

**Comment by loqs** [comment]
> I thought the point of your suggestion above was to define a NASM macro if the build system detected that the C code was being compiled with CET support, but it doesn't seem necessary to do that just to enable shadow stack support.

True if you add `-z,shstk` to the link flags you do not need to touch the ASM.

**Comment by dcommander** [comment]
> True if you add `-z,shstk` to the link flags you do not need to touch the ASM.

Since .note.gnu.property is presumably only supported by the GNU linker, that seems like the best approach, although it would make sense to implement IBT directly in the assembly code, since it is presumably compiler-agnostic and linker-agnostic. Correct me if I'm wrong.

**Comment by loqs** [comment]
> Since .note.gnu.property is presumably only supported by the GNU linker, that seems like the best approach, although it would make sense to implement IBT directly in the assembly code, since it is presumably compiler-agnostic and linker-agnostic. Correct me if I'm wrong.

That is my understanding as well.

**Comment by sthen** [comment]
This patch fixes various SIGILL crashes on OpenBSD/amd64 on a machine with IBT (intel 11th gen/newer).

**Comment by sthen** [comment]
Also, note that it doesn't need any particular version of yasm, the new instructions are implemented as raw bytes via a macro (see https://github.com/libjpeg-turbo/libjpeg-turbo/pull/350/commits/db1afe88c361ceea22c6ac8abdb9b0ff41a39aa2#diff-2dadc4c01bdc4b5ee5ee5694ccf5e5479d905d4a4b5652897d50607b02fc99d4L470) - I am building with yasm 1.3.0 which long pre-dates IBT in CPUs. Builds ok on i386 and amd64 (the patch set requires a small obvious tweak in simd/i386/jchuff-sse2.asm to get it to apply).

**Comment by dcommander** [comment]
> I think the main concern would be on i386 where the opcodes can cause problems on pre-i686 machines. They are a NOP on amd64 so I think would be safe there. I don't think it makes sense to tie this into whether libjpeg-turbo itself is built using CET; the library may be used by other software which results in the checks being enforced.

At the moment, I am not willing to incorporate this feature into the default builds, because I have no way of testing it. Thus, it makes the most sense to enable it based on whether the equivalent feature is enabled in the compiler. If downstream software needs the feature, then the downstream software will need to do a custom build of libjpeg-turbo for now. This is basically an experimental feature from my POV. I want to put it out there so people can test it, and as we all gain confidence that it is innocuous, it can be enabled by default later on.

The fact that there is disagreement over whether to include IBT support makes me hesitant to proceed, so please state your cases for and against.

**Comment by hjl-tools** [comment]
1. ENDBR64 is a NOP on all 64-bit processors.
2. ENDBR32 is a NOP on i686 or newer processors.
3. Linux will enable CET only for 64-bit processors.
4. On Linux, a property note should be added when CET is enabled.   Here is an example https://github.com/hjl-tools/isa-l/commit/f6deb09d4ede51566e2836690260a790f87087bd to add a property note in NASM:
```
%ifdef INTEL_CET_ENABLED
 %ifdef __NASM_VER__
  %if AS_FEATURE_LEVEL >= 10
   %ifidn __OUTPUT_FORMAT__,elf32
section .note.gnu.property  note  alloc noexec align=4
DD 0x00000004,0x0000000c,0x00000005,0x00554e47
DD 0xc0000002,0x00000004,0x00000003
   %endif
   %ifidn __OUTPUT_FORMAT__,elf64
section .note.gnu.property  note  alloc noexec align=8
DD 0x00000004,0x00000010,0x00000005,0x00554e47
DD 0xc0000002,0x00000004,0x00000003,0x00000000
   %endif
  %endif
 %endif
%endif
```

**Comment by dcommander** [comment]
OK, so what I understand at the moment is:
- FreeBSD supports IBT but not shadow stack.
- Linux supports shadow stack but not IBT.
- Shadow stack requires the aforementioned `.note.gnu-property` section for ELF binaries.
- `.note.gnu-property` can either be added explicitly in the assembly code or by passing `-z,shstk` to the linker (but adding it into the assembly code is probably more foolproof.)
- IBT requires `endbr32` and `endbr64`
- Those instructions are no-ops if building for x86-64 or i686 and running on a CPU without CET.
- Those instructions are not compatible with i586 or older CPUs.
- The compiler prevents you from enabling IBT if building for i386-i586.
- There likely is and will be no O/S support for CET on 32-bit CPUs (consistent with the fact that modern O/S's are dropping support for 32-bit CPUs in general.)
 
Someone correct me if I've got any of that wrong.

Questions:
- How will non-ELF platforms, e.g. Windows, handle this?  (I assume macOS will never support CET, because Apple has already moved away from Intel CPUs.)
- We've established that `endbr64` is innocuous on x86-64 CPUs that don't support CET.  Is the same true for `.note.gnu.property`?
- @sthen Why is there any advantage to enabling CET in our assembly code if the compiler doesn't enable it?  Presumably CET isn't enabled in most compilers by default, and if I understand correctly, it wouldn't serve any purpose to have CET support in our assembly code if the C code isn't built with that support.  Downstream packagers can, of course, enable CET in their own libjpeg-turbo builds, but that wouldn't be useful unless the whole O/S is built with CET support. If you're arguing that the official libjpeg-turbo SDKs should include CET support, then that won't be possible at the moment, because they're still built with an older version of GCC.  I can look into upgrading the official builds to use GCC 8 or newer in libjpeg-turbo 3.1.x. (Upgrading the version of GCC used in official builds is a pain, because I have to benchmark it against the version we currently use.)

Assuming my understanding is correct, I feel like the best approach at the moment is:
- Don't include CET support for 32-bit CPUs right now.  It can be included later if/when someone complains.  If/when it is included, it should be enabled only if the compiler enables it.
- Include CET support (both IBT and shadow stack) for 64-bit CPUs in libjpeg-turbo 3.0.3.
- Since CET support would be included in a bug-fix release, don't enable it unless the compiler enables it.  That means that application developers who wish to use CET with libjpeg-turbo 3.0.x will have to do a custom build of libjpeg-turbo, as opposed to using our pre-built SDKs. 
- Enable CET support by default in the next major release of libjpeg-turbo (3.1.x series), which will allow it to go through a beta-test phase.

**Comment by hjl-tools** [comment]
> OK, so what I understand at the moment is:
> 
> * FreeBSD supports IBT but not shadow stack.
> * Linux supports shadow stack but not IBT.

IBT will be enabled on Linux.  But there is no timetable for it.

> * Shadow stack requires the aforementioned `.note.gnu-property` section for ELF binaries.

It is needed for both IBT and SHSTK on Linux.

> * `.note.gnu-property` can either be added explicitly in the assembly code or by passing `-z,shstk` to the linker (but adding it into the assembly code is probably more foolproof.)
> * IBT requires `endbr32` and `endbr64`
> * Those instructions are no-ops if building for x86-64 or i686 and running on a CPU without CET.
> * Those instructions are not compatible with i586 or older CPUs.
> * The compiler prevents you from enabling IBT if building for i386-i586.
> * There likely is and will be no O/S support for CET on 32-bit CPUs (consistent with the fact that modern O/S's are dropping support for 32-bit CPUs in general.)
> 
> Someone correct me if I've got any of that wrong.
> 
> Questions:
> 
> * How will non-ELF platforms, e.g. Windows, handle this?  (I assume macOS will never support CET, because Apple has already moved away from Intel CPUs.)
> * We've established that `endbr64` is innocuous on x86-64 CPUs that don't support CET.  Is the same true for `.note.gnu.property`?

Yes.

> * @sthen Why is there any advantage to enabling CET in our assembly code if the compiler doesn't enable it?  Presumably CET isn't enabled in most compilers by default, and if I understand correctly, it wouldn't serve any purpose to have CET support in our assembly code if the C code isn't built with that support.  Downstream packagers can, of course, enable CET in their own libjpeg-turbo builds, but that wouldn't be useful unless the whole O/S is built with CET support. If you're arguing that the official libjpeg-turbo SDKs should include CET support, then that won't be possible at the moment, because they're still built with an older version of GCC.  I can look into upgrading the official builds to use GCC 8 or newer in libjpeg-turbo 3.1.x. (Upgrading the version of GCC used in official builds is a pain, because I have to benchmark it against the version we currently use.)
> 
> Assuming my understanding is correct, I feel like the best approach at the moment is:
> 
> * Don't include CET support for 32-bit CPUs right now.  It can be included later if/when someone complains.  If/when it is included, it should be enabled only if the compiler enables it.
> * Include CET support (both IBT and shadow stack) for 64-bit CPUs in libjpeg-turbo 3.0.3.
> * Since CET support would be included in a bug-fix release, don't enable it unless the compiler enables it.  That means that application developers who wish to use CET with libjpeg-turbo 3.0.x will have to do a custom build of libjpeg-turbo, as opposed to using our pre-built SDKs.
> * Enable CET support by default in the next major release of libjpeg-turbo (3.1.x series), which will allow it to go through a beta-test phase.

Sounds reasonable to me.

**Comment by sthen** [comment]
Your proposed approach sounds reasonable to me too.

In OpenBSD we are pushing quite hard on IBT and while some patches were needed and it's disabled for some software, we're shipping a lot of packages with it and not seeing problems particularly frequently now (although it will take time to track down everything as some of the missing endbr64 'landing pads' are in infrequently-called functions in various software).

FWIW I get the impression getting shadow stack working in a decent subset of software is going to be a much harder problem to solve, in many cases IBT is just a matter of tracking down where the problems are, the fixes are often pretty simple.

**Comment by loqs** [comment]
@hjl-tools is there a central location to track the state of CET support other than https://gitlab.com/cet-software/?

To try and keep on topic the only test failures I encountered after enabling user space shadow stack support were due to  due to missing support in libjvm.so [libjpeg-turbo-git-3.0.2.r7.g26fc07c8-1-x86_64-check.log](https://gist.github.com/loqs/513adc9dbb901334149f6a46ca250293)

**Comment by dcommander** [comment]
Should now be implemented in the main branch, but please test it, because I have no way of doing so.

**Comment by loqs** [comment]
Testing https://github.com/libjpeg-turbo/libjpeg-turbo/commit/3202feb08aef2d4d1fb35b5af94f1ac92fb993d0 only the expected test failures from the java tests due to missing support in libjvm.so.

**Comment by sthen** [comment]
This seems alright on OpenBSD, tests run ok: "100% tests passed, 0 tests failed out of 590"

**Pull request closed without merging**
