### PR TITLE
Fix building with non-gcc/clang/msvc compiler

### PR DESCRIPTION
**Pull request by carewolf**
Revealed when trying to build for INTEGRITY

### CODE REVIEW

**Comment by dcommander** [comment]
Which compiler specifically needs this?  In other words, how do I reproduce the issue?

**Comment by carewolf** [comment]
The ghs compiler for INTEGRITY. See  https://bugreports.qt.io/browse/QTBUG-93779

But it should be obvious from the code, that it used to check for __GNUC__ and then when the MSVC code path was added, that check was removed, which means any of the rare compilers neither gcc-compatible nor MSVC-compatible would fail.

**Comment by dcommander** [comment]
My point is:

How sure are we that no other compilers than GCC or Clang define `__builtin_clz()`?  Would it make more sense to specifically exclude the INTEGRITY compiler rather than specifically including GCC, Clang, and MSVC?

**Comment by carewolf** [comment]
It is a gcc extension. It is only supported by gcc and compilers mimicking gcc, which means clang, and perhaps ICC, but when they mimick gcc they define the __ GNUC __ define as well, then one you used to check. So using that should be fine.

**Comment by dcommander** [comment]
OK.  I'll just re-add the check for `__GNUC__`, then.  MSVC is already included, because only it defines `_M_ARM` or `_M_ARM64`.

**Comment by carewolf** [comment]
If you were using C++ you could use the __has_builtin check, but that propabably wont work in C mode. Never tried though.

**Comment by carewolf** [comment]
Thank you

**Pull request closed without merging**
