### PR TITLE
bugfix: add bias pattern for h1v2_fancy_upsample

### PR DESCRIPTION
**Pull request by jonathanwright-ARM**
Adds an ordered dither pattern for h1v2_fancy_upsample such that 0.5
will be rounded up or down at alternate pixel locations. Currently
0.5 is always rounded down.

This ordered dither pattern is already used for h2v1_fancy_upsample
and h2v2_fancy_upsample.

### CODE REVIEW

**Comment by dcommander** [comment]
Where is biasing implemented in `h2v2_fancy_upsample()` for the vertical dimension?  I only see it for the horizontal dimension.

**Comment by jonathanwright-ARM** [comment]
Hmmm, it isn't implemented in the vertical dimension for h2v2. I guess it should really?

Either way, since h1v2 is just h2v1 flipped 90 degrees we should have a vertical dither pattern for h1v2. I could change the last sentence to be "Ordered dither patterns are already used for h2v1_fancy_upsample and h2v2_fancy_upsample." - what do you think?

**Comment by dcommander** [comment]
I agree that 4:4:0 should behave like rotated 4:2:2.  This patch improves that situation, but I would expect the following command sequences to produce the same results with the patch, assuming that the 4:2:2 image has iMCU-aligned rows (row width evenly divisible by 16):

```
jpegtran -rotate 90 422.jpg >440.jpg
djpeg 440.jpg >440.ppm
```

```
djpeg 422.jpg >422.ppm
convert -rotate 90 422.ppm 422-rot90.ppm
```

However, they don't.

**Comment by dcommander** [comment]
And as far as h2v2, I have no interest in changing that algorithm, since it is part of the canonical behavior of libjpeg, and changing it would break bitwise compatibility with that legacy software (a lot of downstream applications have come to rely on that behavior.)

**Comment by jonathanwright-ARM** [comment]
I agree that h2v2 should be left alone given the situation with compatibility. It would also be a nightmare updating all of the existing libjpeg-turbo SIMD.

Should we expect the output of those command sequences to be identical? I just tried those commands with a 4:4:4 image (having row and column size both evenly divisible by 16) and got the same sort of noisy diff as with the 4:2:2 image.

**Comment by dcommander** [comment]
Maybe I'm missing something, then.  I was just trying to give myself additional peace of mind that the new implementation of 4:4:0 fancy upsampling is truly correct, since that's a feature that libjpeg never had.

**Comment by jonathanwright-ARM** [comment]
Sure - I want it to be right too before pushing a SIMD implementation. From my viewpoint, the rounding was certainly wrong before - never rounding up 0.5 - and this patch fixes it such that 0.5 is rounded up at every other pixel location. That's not to say there could be something else wrong somewhere - though if there is, it's not obvious to me. Let me know how you want to proceed.

Incidentally, would you be open to receiving a couple of patches adding unit tests for h1v2 fancy upsampling as well as the SIMD function stubs for all of the supported architectures?

**Comment by dcommander** [comment]
Once I can convince myself that the new algorithm is correct, I'll add unit tests for it.  The new SIMD stubs need to be introduced along with your other SIMD modifications.  Those represent a new feature, and given that I went into debt last year because of too much pro bono work on open source code, my policy for this project unfortunately now has to be "no new features without funding."

**Comment by dcommander** [comment]
I was never able to precisely validate the new algorithm, but by reducing the round-off error from other algorithms as much as possible, I was able to come close.

I used

```
cjpeg -rgb -quality 100 -dct float -sample 2x1 {input_image.ppm} >422.jpg
```

to produce a 4:2:2 image with as little error as possible.  I then compared the results of

```
jpegtran -rotate 90 422.jpg >440.jpg
djpeg -dct float 440.jpg >440.ppm
```
and
```
djpeg -dct float 422.jpg >422.ppm
convert -rotate 90 422.ppm 422-rot90.ppm
```

Prior to this patch, with the images I typically use for testing libjpeg-turbo (https://libjpeg-turbo.org/About/Performance), the average error/PSNR between 440.ppm and 422-rot90.ppm was generally about 0.01-0.05/60-68.  After this patch, the average error/PSNR is 0.000001-0.000006/100-110.  In other words, 4:4:0 now produces virtually the same results as rotated 4:2:2.

Commit will be pushed shortly.

**Comment by dcommander** [comment]
Two items of business:
1. I need to add your copyright to the header for jdsample.c.  Please indicate the appropriate entity to which to assign the copyright.
2. Given that your company is not paying for my labor on this issue, I will defer the 4:4:0 unit test and make that part of the integration labor for your new SIMD algorithms.  It is not necessary to add such a unit test to the stable branch, since it does not have any SIMD implementations of the algorithm.

**Comment by jonathanwright-ARM** [comment]
Thanks for going the extra mile validating this.

1. Please assign copyright to "Arm Limited".
2. Sure, that's no problem.

**Pull request closed without merging**
