### PR TITLE
Fix Travis build for Pull Request

### PR DESCRIPTION
**Pull request by mayeut**

### CODE REVIEW

**Comment by mayeut** [comment]
Not working... Need to check build scripts

**Comment by dcommander** [comment]
OK, yes, I noticed this problem too. I wonder if it is related to the `TRAVIS_BRANCH` variable. I read online that there is a special trick for setting the branch properly in pull requests:

https://graysonkoonce.com/getting-the-current-branch-name-during-a-pull-request-in-travis-ci/

The Travis script needs to know the correct branch so it can check out the correct version of the build scripts.

**Comment by mayeut** [comment]
The buildscripts are cloned correctly here:
> `TRAVIS_BRANCH` for builds triggered by a pull request this is the name of the branch targeted by the pull request.

I honestly thought the simple change around openssl stuff would do the trick.
I have a branch I use to do CI in which I changed just that, and, the `TRAVIS_BRANCH` to force it to `dev` when cloning build scripts which is not necessary here given the previous comment.
I will have a look at the build scripts to check what went wrong, I must have missed something.

**Comment by mayeut** [comment]
I've pinpointed the diff between my CI test and Pull Requests:

On a build that's not a PR, travis will clone using the branch name:
```
git clone --depth=50 --branch=travis-PR-test https://github.com/mayeut/libjpeg-turbo.git
cd mayeut/libjpeg-turbo
git checkout -qf f67551286c912ed4cc1c317a5f011f9d7fed17bc
```
On a build that's not a PR, that's a bit different:
```
git clone --depth=50 https://github.com/libjpeg-turbo/libjpeg-turbo.git libjpeg-turbo/libjpeg-turbo
cd libjpeg-turbo/libjpeg-turbo
git fetch origin +refs/pull/217/merge
git checkout -qf FETCH_HEAD
```

Then, in build scripts, the repo is cloned using a specific branch which works in my fork but fails in Pull Request. 

https://github.com/libjpeg-turbo/buildscripts/blob/c8d04d24303bc38b6d59f17c5fcadca149df8b0f/buildljt#L225

**Comment by dcommander** [comment]
I will look at it when I get back to the office tomorrow. The forked repo and PR branch need to be passed from .travis.yml to the build scripts.

**Comment by dcommander** [comment]
I think this is now fixed.  I modified the build scripts so they can perform an "official" build out of an arbitrary directory, which eliminates the need to re-clone the repository and allows PRs to work properly.

**Pull request closed without merging**
