### PR TITLE
Fix unused variable & functions in ARM SIMD

### PR DESCRIPTION
**Pull request by ProgramMax**
When simd/arm/jsimd.c is compiled with __ARM_NEON__ defined there
is a bufsize variable which is defined but never used.

Additionally, parse_proc_cpuinfo() is never used. That function is the
only one which calls check_feature() so it is also never used.

This commit puts all of these under the appropriate #if defined() so
there are no longer unused variables and functions.

### CODE REVIEW

**Comment by dcommander** [comment]
Two questions/comments:
1. It is the convention of the libjpeg-turbo code base to never mix definitions and code, so please move the definition of bufsize accordingly.
2. Who is Google LLC?  Google, Inc. is credited in other parts of the code.  I just need clarification on whether that should apply to this new code as well.

**Comment by dcommander** [comment]
Never mind Question 2.  I looked that up.

**Comment by ProgramMax** [comment]
Yep :)
In 2015 Google, Inc. made its switch to Alphabet, Inc. which holds Google LLC.

As for your first comment, I'm sorry about that. I didn't do my due diligence to make sure I was conforming to style. Thank you for catching that.

I think this new commit will match your style. Please let me know if I can further improve anything. :)

**Comment by ProgramMax** [comment]
The AppVeyor build is failing because nasm.us is down right now. It can't fetch NASM.

**Comment by dcommander** [comment]
> The AppVeyor build is failing because nasm.us is down right now. It can't fetch NASM.

Yeah, I know.  That unfortunately happens from time to time.

**Pull request closed without merging**
