### PR TITLE
reuse output buffer in jpeg_stdio_dest

### PR DESCRIPTION
**Pull request by PeterRK**

### CODE REVIEW

**Comment by dcommander** [comment]
I will never accept a pull request without a thorough description justifying the necessity of the code, including steps to reproduce a problem that the pull request purports to fix or an example of a use case that the pull request enables.  libjpeg-turbo is an ISO reference implementation of the JPEG standard, and it directly or indirectly has millions of users, so any modifications to it need to be very carefully developed.  Please refer to our contribution guidelines: https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/.github/CONTRIBUTING.md

In this case, `jpeg_stdio_dest()` is a libjpeg API function, so its behavior is canonical.  Any modifications to that function would need to be backward compatible, and I would need to thoroughly understand what you're trying to achieve with this patch.  At first glance, I can't figure that out.  `dest->buffer` is opaque from the point of view of the calling program, and the `init_destination()` method of the destination manager is invoked only once, so as far as I can tell, your code accomplishes nothing.  Please explain and justify your modification.

**Comment by PeterRK** [comment]
Yes, it is meaningless to reuse output buffer if init_destination is designed to be invoked only once, but I found jpeg_start_compress calls init_destination without check. In my case, jpeg_stdio_dest, jpeg_start_compress, jpeg_write_scanlines and jpeg_finish_compress are called in a loop without any error. Is it illegal to reuse jpeg_compress_struct for multiple images with different stdio_dest?

This patch doesn't focus on the problem. The only advantage of it is looking harmless. I hope for a real solution. Thank you.

**Comment by dcommander** [comment]
Please post code demonstrating what you are trying to accomplish, as well as a description of how the behavior is not as you expect.

It is not illegal to reuse a `jpeg_compress_struct` instance for multiple images, but it may not be possible to use the default stdio destination manager for that.  That's why I need to see specific code-- so I can figure out what you're trying to accomplish and how that might be accomplished using the libjpeg API.

**Comment by dcommander** [comment]
I don't see any problem with that code.  When using the stdio destination manager, the destination manager's buffer will be allocated in the `JPOOL_IMAGE` memory pool in the body of `init_destination()`, which is called within the body of `jpeg_start_compress()`.  That memory pool will then be freed in the body of `jpeg_abort()`, which is called within the body of `jpeg_finish_compress()`.  What specifically is failing?

**Comment by dcommander** [comment]
Also note-- `jpeg_write_scanlines()` is not guaranteed to write as many scanlines as you request.  You should keep calling that function in a loop (refer to **example.txt** in the libjpeg-turbo source tree) while `cinfo.next_scanline` < `cinfo.image_height`.

**Comment by PeterRK** [comment]
Thanks.

**Pull request closed without merging**
