### PR TITLE
Port some arm NEON optimized functions to arm64

### PR DESCRIPTION
**Pull request by mayeut**
The following functions have been ported to arm64:
- jsimd_fdct_ifast
- jsimd_fdct_islow
- jsimd_quantize
- jsimd_convsamp
- jsimd_rgb_ycc_convert
- jsimd_h2v1_downsample
- jsimd_h2v2_downsample

In short:
clang arm64: +59%
clang arm64 with NEON huffman encoding #42: +136%

In details:
```
Matt$ clang --version
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
```
Here's the partial output for `./tjbench ../libjpeg-turbo/testimages/vgl_6434_0018a.bmp 95 -rgb -subsamp 444 -componly` on an iPhone 5S.

clang arm64
```
Frame rate:         1088.008769 fps
Output image size:  14225 bytes
Compression ratio:  2.409279:1
Throughput:         12.429412 Megapixels/sec
Output bit stream:  123.815398 Megabits/sec
```
clang arm64 with new NEON functions
```
Frame rate:         1731.323966 fps
Output image size:  14225 bytes
Compression ratio:  2.409279:1
Throughput:         19.778645 Megapixels/sec
Output bit stream:  197.024667 Megabits/sec
```
clang arm64 with new NEON functions + NEON Huffman encoding #42
```
Frame rate:         2570.224252 fps
Output image size:  14225 bytes
Compression ratio:  2.409279:1
Throughput:         29.362242 Megapixels/sec
Output bit stream:  292.491520 Megabits/sec
```

### CODE REVIEW

**Comment by mayeut** [comment]
I added jsimd_fdct_islow.

In short:
clang arm64: +58%
clang arm64 with NEON huffman encoding #42: +103%

In details
```
Matt$ clang --version
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
```
Here's the partial output for `./tjbench ../libjpeg-turbo/testimages/vgl_6434_0018a.bmp 100 -rgb -subsamp 444 -componly` on an iPhone 5S.

clang arm64
```
Frame rate:         978.450934 fps
Output image size:  26018 bytes
Compression ratio:  1.317242:1
Throughput:         11.177823 Megapixels/sec
Output bit stream:  203.658691 Megabits/sec
```
clang arm64 with new NEON functions
```
Frame rate:         1543.387047 fps
Output image size:  26018 bytes
Compression ratio:  1.317242:1
Throughput:         17.631654 Megapixels/sec
Output bit stream:  321.246754 Megabits/sec
```
clang arm64 with new NEON functions + NEON Huffman encoding #42
```
Frame rate:         1986.506602 fps
Output image size:  26018 bytes
Compression ratio:  1.317242:1
Throughput:         22.693851 Megapixels/sec
Output bit stream:  413.479430 Megabits/sec
```

**Comment by dcommander** [comment]
Are you testing with a jailbroken iPhone? I have a 6S, but since there is no jailbreak yet for iOS 9.1, I can't yet figure out how to test libjpeg-turbo with ARM64.

Also, how did you run the regression tests? On ARM32, I have some custom scripts that copy the necessary files to my jailbroken 4S and run them via SSH.

**Comment by mayeut** [comment]
@dcommander,
I did not run regressions test from libjpeg-turbo as one can do by running `make test`.
I created a UI wrapper for `tjbench`in Xcode and tested only the 2 command lines above which should cover those algorithms for non regression.  Result images are of course bitwise identical with & without those NEON optimized functions.

**Comment by dcommander** [comment]
There are some corner cases that 'make test' covers that simply running tcbench doesn't. I think I may have found a way to run it, though. I'm going to work on integrating these patches next week, so I'll let you know what I find.

**Comment by mayeut** [comment]
I added jsimd_h2v1_downsample.

In short:
clang arm64: +72%
clang arm64 with NEON huffman encoding #42: +137%

In details
```
Matt$ clang --version
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
```
Here's the partial output for `./tjbench ../libjpeg-turbo/testimages/vgl_6434_0018a.bmp 95 -rgb -subsamp 422 -componly` on an iPhone 5S.

clang arm64
```
Frame rate:         1339.262827 fps
Output image size:  11058 bytes
Compression ratio:  3.099295:1
Throughput:         15.299739 Megapixels/sec
Output bit stream:  118.476547 Megabits/sec
```
clang arm64 with new NEON functions
```
Frame rate:         2305.096789 fps
Output image size:  11058 bytes
Compression ratio:  3.099295:1
Throughput:         26.333426 Megapixels/sec
Output bit stream:  203.918082 Megabits/sec
```
clang arm64 with new NEON functions + NEON Huffman encoding #42
```
Frame rate:         3172.737669 fps
Output image size:  11058 bytes
Compression ratio:  3.099295:1
Throughput:         36.245355 Megapixels/sec
Output bit stream:  280.673065 Megabits/sec
```

**Comment by mayeut** [comment]
I added jsimd_h2v2_downsample.

In short:
clang arm64: +79%
clang arm64 with NEON huffman encoding #42: +134%

In details
```
Matt$ clang --version
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
```
Here's the partial output for `./tjbench ../libjpeg-turbo/testimages/vgl_6434_0018a.bmp 95 -rgb -subsamp 420 -componly` on an iPhone 5S.

clang arm64
```
Frame rate:         1665.761715 fps
Output image size:  9077 bytes
Compression ratio:  3.775697:1
Throughput:         19.029662 Megapixels/sec
Output bit stream:  120.960953 Megabits/sec
```
clang arm64 with new NEON functions
```
Frame rate:         2985.667883 fps
Output image size:  9077 bytes
Compression ratio:  3.775697:1
Throughput:         34.108270 Megapixels/sec
Output bit stream:  216.807259 Megabits/sec
```
clang arm64 with new NEON functions + NEON Huffman encoding #42
```
Frame rate:         3893.282300 fps
Output image size:  9077 bytes
Compression ratio:  3.775697:1
Throughput:         44.476857 Megapixels/sec
Output bit stream:  282.714588 Megabits/sec
```

**Comment by dcommander** [comment]
The images in testimages/ are not large enough to make very good benchmarks. For quick & dirty performance testing, I generally use artificial.ppm and nightshot_iso_100.ppm from http://imagecompression.info/test_images/ (RGB 8-bit)

**Comment by mayeut** [comment]
In short:
artificial.ppm 444 Q100 clang arm64: +90%
artificial.ppm 444 Q100 clang arm64 with NEON huffman encoding #42: +163%
artificial.ppm 444 Q95 clang arm64: +109%
artificial.ppm 444 Q95 clang arm64 with NEON huffman encoding #42: +185%
artificial.ppm 422 Q95 clang arm64: +127%
artificial.ppm 422 Q95 clang arm64 with NEON huffman encoding #42: +211%
artificial.ppm 420 Q95 clang arm64: +136%
artificial.ppm 420 Q95 clang arm64 with NEON huffman encoding #42: +220%
nightshot_iso_100.ppm 444 Q100 clang arm64: +56%
nightshot_iso_100.ppm 444 Q100 clang arm64 with NEON huffman encoding #42: +155%
nightshot_iso_100.ppm 444 Q95 clang arm64: +102%
nightshot_iso_100.ppm 444 Q95 clang arm64 with NEON huffman encoding #42: +171%
nightshot_iso_100.ppm 422 Q95 clang arm64: +115%
nightshot_iso_100.ppm 422 Q95 clang arm64 with NEON huffman encoding #42: +194%
nightshot_iso_100.ppm 420 Q95 clang arm64: +122%
nightshot_iso_100.ppm 420 Q95 clang arm64 with NEON huffman encoding #42: +201%

In details
```
Matt$ clang --version
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
```
Here's the partial output for `./tjbench IMAGE Q -rgb -subsamp SUBSAMP -componly` on an iPhone 5S.

clang arm64
```
>>>>>  RGB (Top-down) <--> JPEG 4:4:4 Q100  <<<<<

Image size: 3072 x 2048
Compress      --> Frame rate:         2.557683 fps
                  Output image size:  2815066 bytes
                  Compression ratio:  6.704769:1
                  Throughput:         16.091550 Megapixels/sec
                  Output bit stream:  57.600371 Megabits/sec
Reference image written to artificial_444_Q100.jpg


>>>>>  RGB (Top-down) <--> JPEG 4:4:4 Q95  <<<<<

Image size: 3072 x 2048
Compress      --> Frame rate:         3.029443 fps
                  Output image size:  1319596 bytes
                  Compression ratio:  14.303141:1
                  Throughput:         19.059605 Megapixels/sec
                  Output bit stream:  31.981123 Megabits/sec
Reference image written to artificial_444_Q95.jpg


>>>>>  RGB (Top-down) <--> JPEG 4:2:2 Q95  <<<<<

Image size: 3072 x 2048
Compress      --> Frame rate:         4.029654 fps
                  Output image size:  1130261 bytes
                  Compression ratio:  16.699123:1
                  Throughput:         25.352394 Megapixels/sec
                  Output bit stream:  36.436490 Megabits/sec
Reference image written to artificial_422_Q95.jpg


>>>>>  RGB (Top-down) <--> JPEG 4:2:0 Q95  <<<<<

Image size: 3072 x 2048
Compress      --> Frame rate:         4.831760 fps
                  Output image size:  1006900 bytes
                  Compression ratio:  18.745027:1
                  Throughput:         30.398803 Megapixels/sec
                  Output bit stream:  38.920790 Megabits/sec
Reference image written to artificial_420_Q95.jpg


>>>>>  RGB (Top-down) <--> JPEG 4:4:4 Q100  <<<<<

Image size: 3136 x 2352
Compress      --> Frame rate:         1.654537 fps
                  Output image size:  7046047 bytes
                  Compression ratio:  3.140430:1
                  Throughput:         12.203652 Megapixels/sec
                  Output bit stream:  93.263554 Megabits/sec
Reference image written to nightshot_iso_100_444_Q100.jpg


>>>>>  RGB (Top-down) <--> JPEG 4:4:4 Q95  <<<<<

Image size: 3136 x 2352
Compress      --> Frame rate:         2.507929 fps
                  Output image size:  2040975 bytes
                  Compression ratio:  10.841689:1
                  Throughput:         18.498164 Megapixels/sec
                  Output bit stream:  40.948964 Megabits/sec
Reference image written to nightshot_iso_100_444_Q95.jpg


>>>>>  RGB (Top-down) <--> JPEG 4:2:2 Q95  <<<<<

Image size: 3136 x 2352
Compress      --> Frame rate:         3.369894 fps
                  Output image size:  1641629 bytes
                  Compression ratio:  13.479060:1
                  Throughput:         24.855908 Megapixels/sec
                  Output bit stream:  44.256927 Megabits/sec
Reference image written to nightshot_iso_100_422_Q95.jpg


>>>>>  RGB (Top-down) <--> JPEG 4:2:0 Q95  <<<<<

Image size: 3136 x 2352
Compress      --> Frame rate:         4.081256 fps
                  Output image size:  1425172 bytes
                  Compression ratio:  15.526278:1
                  Throughput:         30.102819 Megapixels/sec
                  Output bit stream:  46.531929 Megabits/sec
Reference image written to nightshot_iso_100_420_Q95.jpg
```
clang arm64 with new NEON functions
```
>>>>>  RGB (Top-down) <--> JPEG 4:4:4 Q100  <<<<<

Image size: 3072 x 2048
Compress      --> Frame rate:         4.802114 fps
                  Output image size:  2815066 bytes
                  Compression ratio:  6.704769:1
                  Throughput:         30.212287 Megapixels/sec
                  Output bit stream:  108.146135 Megabits/sec
Reference image written to artificial_444_Q100.jpg


>>>>>  RGB (Top-down) <--> JPEG 4:4:4 Q95  <<<<<

Image size: 3072 x 2048
Compress      --> Frame rate:         6.335573 fps
                  Output image size:  1319596 bytes
                  Compression ratio:  14.303141:1
                  Throughput:         39.859981 Megapixels/sec
                  Output bit stream:  66.883178 Megabits/sec
Reference image written to artificial_444_Q95.jpg


>>>>>  RGB (Top-down) <--> JPEG 4:2:2 Q95  <<<<<

Image size: 3072 x 2048
Compress      --> Frame rate:         9.151223 fps
                  Output image size:  1130261 bytes
                  Compression ratio:  16.699123:1
                  Throughput:         57.574515 Megapixels/sec
                  Output bit stream:  82.746162 Megabits/sec
Reference image written to artificial_422_Q95.jpg


>>>>>  RGB (Top-down) <--> JPEG 4:2:0 Q95  <<<<<

Image size: 3072 x 2048
Compress      --> Frame rate:         11.397906 fps
                  Output image size:  1006900 bytes
                  Compression ratio:  18.745027:1
                  Throughput:         71.709427 Megapixels/sec
                  Output bit stream:  91.812416 Megabits/sec
Reference image written to artificial_420_Q95.jpg


>>>>>  RGB (Top-down) <--> JPEG 4:4:4 Q100  <<<<<

Image size: 3136 x 2352
Compress      --> Frame rate:         2.578108 fps
                  Output image size:  7046047 bytes
                  Compression ratio:  3.140430:1
                  Throughput:         19.015797 Megapixels/sec
                  Output bit stream:  145.323779 Megabits/sec
Reference image written to nightshot_iso_100_444_Q100.jpg


>>>>>  RGB (Top-down) <--> JPEG 4:4:4 Q95  <<<<<

Image size: 3136 x 2352
Compress      --> Frame rate:         5.057011 fps
                  Output image size:  2040975 bytes
                  Compression ratio:  10.841689:1
                  Throughput:         37.299868 Megapixels/sec
                  Output bit stream:  82.569868 Megabits/sec
Reference image written to nightshot_iso_100_444_Q95.jpg


>>>>>  RGB (Top-down) <--> JPEG 4:2:2 Q95  <<<<<

Image size: 3136 x 2352
Compress      --> Frame rate:         7.242953 fps
                  Output image size:  1641629 bytes
                  Compression ratio:  13.479060:1
                  Throughput:         53.423094 Megapixels/sec
                  Output bit stream:  95.121933 Megabits/sec
Reference image written to nightshot_iso_100_422_Q95.jpg


>>>>>  RGB (Top-down) <--> JPEG 4:2:0 Q95  <<<<<

Image size: 3136 x 2352
Compress      --> Frame rate:         9.077207 fps
                  Output image size:  1425172 bytes
                  Compression ratio:  15.526278:1
                  Throughput:         66.952319 Megapixels/sec
                  Output bit stream:  103.492654 Megabits/sec
Reference image written to nightshot_iso_100_420_Q95.jpg
```
clang arm64 with new NEON functions + NEON Huffman encoding #42
```
>>>>>  RGB (Top-down) <--> JPEG 4:4:4 Q100  <<<<<

Image size: 3072 x 2048
Compress      --> Frame rate:         6.717357 fps
                  Output image size:  2815066 bytes
                  Compression ratio:  6.704769:1
                  Throughput:         42.261957 Megapixels/sec
                  Output bit stream:  151.278431 Megabits/sec
Reference image written to artificial_444_Q100.jpg


>>>>>  RGB (Top-down) <--> JPEG 4:4:4 Q95  <<<<<

Image size: 3072 x 2048
Compress      --> Frame rate:         8.640555 fps
                  Output image size:  1319596 bytes
                  Compression ratio:  14.303141:1
                  Throughput:         54.361670 Megapixels/sec
                  Output bit stream:  91.216332 Megabits/sec
Reference image written to artificial_444_Q95.jpg


>>>>>  RGB (Top-down) <--> JPEG 4:2:2 Q95  <<<<<

Image size: 3072 x 2048
Compress      --> Frame rate:         12.527620 fps
                  Output image size:  1130261 bytes
                  Compression ratio:  16.699123:1
                  Throughput:         78.816973 Megapixels/sec
                  Output bit stream:  113.275847 Megabits/sec
Reference image written to artificial_422_Q95.jpg


>>>>>  RGB (Top-down) <--> JPEG 4:2:0 Q95  <<<<<

Image size: 3072 x 2048
Compress      --> Frame rate:         15.446612 fps
                  Output image size:  1006900 bytes
                  Compression ratio:  18.745027:1
                  Throughput:         97.181677 Megapixels/sec
                  Output bit stream:  124.425546 Megabits/sec
Reference image written to artificial_420_Q95.jpg


>>>>>  RGB (Top-down) <--> JPEG 4:4:4 Q100  <<<<<

Image size: 3136 x 2352
Compress      --> Frame rate:         4.220119 fps
                  Output image size:  7046047 bytes
                  Compression ratio:  3.140430:1
                  Throughput:         31.127056 Megapixels/sec
                  Output bit stream:  237.881246 Megabits/sec
Reference image written to nightshot_iso_100_444_Q100.jpg


>>>>>  RGB (Top-down) <--> JPEG 4:4:4 Q95  <<<<<

Image size: 3136 x 2352
Compress      --> Frame rate:         6.807306 fps
                  Output image size:  2040975 bytes
                  Compression ratio:  10.841689:1
                  Throughput:         50.209821 Megapixels/sec
                  Output bit stream:  111.148339 Megabits/sec
Reference image written to nightshot_iso_100_444_Q95.jpg


>>>>>  RGB (Top-down) <--> JPEG 4:2:2 Q95  <<<<<

Image size: 3136 x 2352
Compress      --> Frame rate:         9.920020 fps
                  Output image size:  1641629 bytes
                  Compression ratio:  13.479060:1
                  Throughput:         73.168800 Megapixels/sec
                  Output bit stream:  130.279943 Megabits/sec
Reference image written to nightshot_iso_100_422_Q95.jpg


>>>>>  RGB (Top-down) <--> JPEG 4:2:0 Q95  <<<<<

Image size: 3136 x 2352
Compress      --> Frame rate:         12.298823 fps
                  Output image size:  1425172 bytes
                  Compression ratio:  15.526278:1
                  Throughput:         90.714542 Megapixels/sec
                  Output bit stream:  140.223502 Megabits/sec
Reference image written to nightshot_iso_100_420_Q95.jpg
```

**Comment by dcommander** [comment]
Getting some assembler errors when attempting to compile this on ARM64 Linux:

      CPPAS    jsimd_arm64_neon.lo
    ../../simd/jsimd_arm64_neon.S: Assembler messages:
    ../../simd/jsimd_arm64_neon.S:2441: Error: operand mismatch -- `mov v22.4s,v18.4s'
    ../../simd/jsimd_arm64_neon.S:2442: Error: operand mismatch -- `mov v25.4s,v24.4s'
    ../../simd/jsimd_arm64_neon.S:2547: Error: operand mismatch -- `mov v22.4s,v18.4s'
    ../../simd/jsimd_arm64_neon.S:2548: Error: operand mismatch -- `mov v25.4s,v24.4s'
    ../../simd/jsimd_arm64_neon.S:2637: Error: unknown register alias 'DSP1'
    ../../simd/jsimd_arm64_neon.S:2638: Error: unknown register alias 'DSP2'
    ../../simd/jsimd_arm64_neon.S:2639: Error: unknown register alias 'DSP2H'

**Comment by dcommander** [comment]
iOS build also fails:

```
  CPPAS    jsimd_arm64_neon.lo
../../simd/jsimd_arm64_neon.S:59:14: error: unqualified, assembler-local label name expected
    adr x13, jsimd_extrgb_ycc_neon_consts
             ^
../../simd/jsimd_arm64_neon.S:73:5: error: unrecognized instruction mnemonic
    blt 9f
    ^
../../simd/jsimd_arm64_neon.S:78:15: error: register expected
    ldr x11, [OUTPUT_BUF, x3, lsl #3]
              ^
../../simd/jsimd_arm64_neon.S:84:5: error: unrecognized instruction mnemonic
    blt 3f
    ^
../../simd/jsimd_arm64_neon.S:116:5: error: unrecognized instruction mnemonic
    blt 2f
    ^
../../simd/jsimd_arm64_neon.S:164:5: error: unrecognized instruction mnemonic
    bge 1b
    ^
../../simd/jsimd_arm64_neon.S:182:5: error: unrecognized instruction mnemonic
    beq 8f
    ^
../../simd/jsimd_arm64_neon.S:185:5: error: unrecognized instruction mnemonic
    beq 3f
    ^
../../simd/jsimd_arm64_neon.S:192:5: error: unrecognized instruction mnemonic
    beq 4f
    ^
../../simd/jsimd_arm64_neon.S:197:5: error: unrecognized instruction mnemonic
    beq 5f
    ^
../../simd/jsimd_arm64_neon.S:241:5: error: unrecognized instruction mnemonic
    beq 6f
    ^
../../simd/jsimd_arm64_neon.S:256:5: error: unrecognized instruction mnemonic
    beq 7f
    ^
../../simd/jsimd_arm64_neon.S:265:5: error: unrecognized instruction mnemonic
    beq 8f
    ^
../../simd/jsimd_arm64_neon.S:271:5: error: unrecognized instruction mnemonic
    bgt 0b
    ^
../../simd/jsimd_arm64_neon.S:59:14: error: unqualified, assembler-local label name expected
    adr x13, jsimd_extbgr_ycc_neon_consts
             ^
../../simd/jsimd_arm64_neon.S:73:5: error: unrecognized instruction mnemonic
    blt 9f
    ^
../../simd/jsimd_arm64_neon.S:78:15: error: register expected
    ldr x11, [OUTPUT_BUF, x3, lsl #3]
              ^
../../simd/jsimd_arm64_neon.S:84:5: error: unrecognized instruction mnemonic
    blt 3f
    ^
../../simd/jsimd_arm64_neon.S:116:5: error: unrecognized instruction mnemonic
    blt 2f
    ^
../../simd/jsimd_arm64_neon.S:164:5: error: unrecognized instruction mnemonic
    bge 1b
    ^
../../simd/jsimd_arm64_neon.S:182:5: error: unrecognized instruction mnemonic
    beq 8f
    ^
../../simd/jsimd_arm64_neon.S:185:5: error: unrecognized instruction mnemonic
    beq 3f
    ^
../../simd/jsimd_arm64_neon.S:192:5: error: unrecognized instruction mnemonic
    beq 4f
    ^
../../simd/jsimd_arm64_neon.S:197:5: error: unrecognized instruction mnemonic
    beq 5f
    ^
../../simd/jsimd_arm64_neon.S:241:5: error: unrecognized instruction mnemonic
    beq 6f
    ^
../../simd/jsimd_arm64_neon.S:256:5: error: unrecognized instruction mnemonic
    beq 7f
    ^
../../simd/jsimd_arm64_neon.S:265:5: error: unrecognized instruction mnemonic
    beq 8f
    ^
../../simd/jsimd_arm64_neon.S:271:5: error: unrecognized instruction mnemonic
    bgt 0b
    ^
../../simd/jsimd_arm64_neon.S:59:14: error: unqualified, assembler-local label name expected
    adr x13, jsimd_extrgbx_ycc_neon_consts
             ^
../../simd/jsimd_arm64_neon.S:73:5: error: unrecognized instruction mnemonic
    blt 9f
    ^
../../simd/jsimd_arm64_neon.S:78:15: error: register expected
    ldr x11, [OUTPUT_BUF, x3, lsl #3]
              ^
../../simd/jsimd_arm64_neon.S:84:5: error: unrecognized instruction mnemonic
    blt 3f
    ^
../../simd/jsimd_arm64_neon.S:116:5: error: unrecognized instruction mnemonic
    blt 2f
    ^
../../simd/jsimd_arm64_neon.S:164:5: error: unrecognized instruction mnemonic
    bge 1b
    ^
../../simd/jsimd_arm64_neon.S:182:5: error: unrecognized instruction mnemonic
    beq 8f
    ^
../../simd/jsimd_arm64_neon.S:185:5: error: unrecognized instruction mnemonic
    beq 3f
    ^
../../simd/jsimd_arm64_neon.S:192:5: error: unrecognized instruction mnemonic
    beq 4f
    ^
../../simd/jsimd_arm64_neon.S:197:5: error: unrecognized instruction mnemonic
    beq 5f
    ^
../../simd/jsimd_arm64_neon.S:241:5: error: unrecognized instruction mnemonic
    beq 6f
    ^
../../simd/jsimd_arm64_neon.S:256:5: error: unrecognized instruction mnemonic
    beq 7f
    ^
../../simd/jsimd_arm64_neon.S:265:5: error: unrecognized instruction mnemonic
    beq 8f
    ^
../../simd/jsimd_arm64_neon.S:271:5: error: unrecognized instruction mnemonic
    bgt 0b
    ^
../../simd/jsimd_arm64_neon.S:59:14: error: unqualified, assembler-local label name expected
    adr x13, jsimd_extbgrx_ycc_neon_consts
             ^
../../simd/jsimd_arm64_neon.S:73:5: error: unrecognized instruction mnemonic
    blt 9f
    ^
../../simd/jsimd_arm64_neon.S:78:15: error: register expected
    ldr x11, [OUTPUT_BUF, x3, lsl #3]
              ^
../../simd/jsimd_arm64_neon.S:84:5: error: unrecognized instruction mnemonic
    blt 3f
    ^
../../simd/jsimd_arm64_neon.S:116:5: error: unrecognized instruction mnemonic
    blt 2f
    ^
../../simd/jsimd_arm64_neon.S:164:5: error: unrecognized instruction mnemonic
    bge 1b
    ^
../../simd/jsimd_arm64_neon.S:182:5: error: unrecognized instruction mnemonic
    beq 8f
    ^
../../simd/jsimd_arm64_neon.S:185:5: error: unrecognized instruction mnemonic
    beq 3f
    ^
../../simd/jsimd_arm64_neon.S:192:5: error: unrecognized instruction mnemonic
    beq 4f
    ^
../../simd/jsimd_arm64_neon.S:197:5: error: unrecognized instruction mnemonic
    beq 5f
    ^
../../simd/jsimd_arm64_neon.S:241:5: error: unrecognized instruction mnemonic
    beq 6f
    ^
../../simd/jsimd_arm64_neon.S:256:5: error: unrecognized instruction mnemonic
    beq 7f
    ^
../../simd/jsimd_arm64_neon.S:265:5: error: unrecognized instruction mnemonic
    beq 8f
    ^
../../simd/jsimd_arm64_neon.S:271:5: error: unrecognized instruction mnemonic
    bgt 0b
    ^
../../simd/jsimd_arm64_neon.S:59:14: error: unqualified, assembler-local label name expected
    adr x13, jsimd_extxbgr_ycc_neon_consts
             ^
../../simd/jsimd_arm64_neon.S:73:5: error: unrecognized instruction mnemonic
    blt 9f
    ^
../../simd/jsimd_arm64_neon.S:78:15: error: register expected
    ldr x11, [OUTPUT_BUF, x3, lsl #3]
              ^
../../simd/jsimd_arm64_neon.S:84:5: error: unrecognized instruction mnemonic
    blt 3f
    ^
../../simd/jsimd_arm64_neon.S:116:5: error: unrecognized instruction mnemonic
    blt 2f
    ^
../../simd/jsimd_arm64_neon.S:164:5: error: unrecognized instruction mnemonic
    bge 1b
    ^
../../simd/jsimd_arm64_neon.S:182:5: error: unrecognized instruction mnemonic
    beq 8f
    ^
../../simd/jsimd_arm64_neon.S:185:5: error: unrecognized instruction mnemonic
    beq 3f
    ^
../../simd/jsimd_arm64_neon.S:192:5: error: unrecognized instruction mnemonic
    beq 4f
    ^
../../simd/jsimd_arm64_neon.S:197:5: error: unrecognized instruction mnemonic
    beq 5f
    ^
../../simd/jsimd_arm64_neon.S:241:5: error: unrecognized instruction mnemonic
    beq 6f
    ^
../../simd/jsimd_arm64_neon.S:256:5: error: unrecognized instruction mnemonic
    beq 7f
    ^
../../simd/jsimd_arm64_neon.S:265:5: error: unrecognized instruction mnemonic
    beq 8f
    ^
../../simd/jsimd_arm64_neon.S:271:5: error: unrecognized instruction mnemonic
    bgt 0b
    ^
../../simd/jsimd_arm64_neon.S:59:14: error: unqualified, assembler-local label name expected
    adr x13, jsimd_extxrgb_ycc_neon_consts
             ^
../../simd/jsimd_arm64_neon.S:73:5: error: unrecognized instruction mnemonic
    blt 9f
    ^
../../simd/jsimd_arm64_neon.S:78:15: error: register expected
    ldr x11, [OUTPUT_BUF, x3, lsl #3]
              ^
../../simd/jsimd_arm64_neon.S:84:5: error: unrecognized instruction mnemonic
    blt 3f
    ^
../../simd/jsimd_arm64_neon.S:116:5: error: unrecognized instruction mnemonic
    blt 2f
    ^
../../simd/jsimd_arm64_neon.S:164:5: error: unrecognized instruction mnemonic
    bge 1b
    ^
../../simd/jsimd_arm64_neon.S:182:5: error: unrecognized instruction mnemonic
    beq 8f
    ^
../../simd/jsimd_arm64_neon.S:185:5: error: unrecognized instruction mnemonic
    beq 3f
    ^
../../simd/jsimd_arm64_neon.S:192:5: error: unrecognized instruction mnemonic
    beq 4f
    ^
../../simd/jsimd_arm64_neon.S:197:5: error: unrecognized instruction mnemonic
    beq 5f
    ^
../../simd/jsimd_arm64_neon.S:241:5: error: unrecognized instruction mnemonic
    beq 6f
    ^
../../simd/jsimd_arm64_neon.S:256:5: error: unrecognized instruction mnemonic
    beq 7f
    ^
../../simd/jsimd_arm64_neon.S:265:5: error: unrecognized instruction mnemonic
    beq 8f
    ^
../../simd/jsimd_arm64_neon.S:271:5: error: unrecognized instruction mnemonic
    bgt 0b
    ^
../../simd/jsimd_arm64_neon.S:58:13: error: unqualified, assembler-local label name expected
    adr x9, jsimd_fdct_islow_neon_consts
            ^
../../simd/jsimd_arm64_neon.S:2467:21: error: invalid operand for instruction
        orr v22.4s, v18.4s, v18.4s
                    ^
../../simd/jsimd_arm64_neon.S:2468:21: error: invalid operand for instruction
        orr v25.4s, v24.4s, v24.4s
                    ^
../../simd/jsimd_arm64_neon.S:2598:21: error: invalid operand for instruction
        orr v22.4s, v18.4s, v18.4s
                    ^
../../simd/jsimd_arm64_neon.S:2599:21: error: invalid operand for instruction
        orr v25.4s, v24.4s, v24.4s
                    ^
../../simd/jsimd_arm64_neon.S:58:13: error: unqualified, assembler-local label name expected
    adr x9, jsimd_fdct_ifast_neon_consts
            ^
../../simd/jsimd_arm64_neon.S:2771:5: error: unrecognized instruction mnemonic
    bne 1b
    ^
../../simd/jsimd_arm64_neon.S:114:5: error: unrecognized instruction mnemonic
    bne 1b
    ^
../../simd/jsimd_arm64_neon.S:59:14: error: unqualified, assembler-local label name expected
    adr x13, jsimd_h2v1_downsample_neon_consts
             ^
../../simd/jsimd_arm64_neon.S:68:5: error: unrecognized instruction mnemonic
    beq 3f
    ^
../../simd/jsimd_arm64_neon.S:76:5: error: unrecognized instruction mnemonic
    bne 2b
    ^
../../simd/jsimd_arm64_neon.S:87:5: error: unrecognized instruction mnemonic
    bne 1b
    ^
../../simd/jsimd_arm64_neon.S:60:14: error: unqualified, assembler-local label name expected
    adr x13, jsimd_h2v2_downsample_neon_consts
             ^
../../simd/jsimd_arm64_neon.S:71:5: error: unrecognized instruction mnemonic
    beq 3f
    ^
../../simd/jsimd_arm64_neon.S:82:5: error: unrecognized instruction mnemonic
    bne 2b
    ^
../../simd/jsimd_arm64_neon.S:98:5: error: unrecognized instruction mnemonic
    bne 1b
    ^
```

Built with:
```
IOS_PLATFORMDIR="/Applications/Xcode51.app/Contents/Developer/Platforms/iPhoneOS.platform"
IOS_SYSROOT="$IOS_PLATFORMDIR/Developer/SDKs/iPhoneOS7.1.sdk"
IOS_CFLAGS="-arch arm64 -miphoneos-version-min=7.0"
export host_alias=aarch64-apple-darwin
export CC="/Applications/Xcode51.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang"
export CFLAGS="-isysroot $IOS_SYSROOT -O3 $IOS_CFLAGS -funwind-tables"
sh ../configure --with-pic --with-simd
```

**Comment by dcommander** [comment]
Some additional notes:
* Please squash all of these into one commit.
* I would prefer that you solve the Huffman ARM64 issue first, then rebase these on top of that.
* Please be mindful of end-of-line spacing.  Your code tends to have a lot of unnecessary whitespace.

**Comment by mayeut** [comment]
I will work on all of that.

**Comment by mayeut** [comment]
Squashed in 1 commit in #49

**Pull request closed without merging**
