### PR TITLE
SSE4.2 and AVX2 intriniscs, for faster encoding

### PR DESCRIPTION
**Pull request by vkrasnov**
To enable configure with CFLAGS="-O3 -msse4.2" or CFLAGS="-O3 -mavx2"

The improvements are described in https://blog.cloudflare.com/doubling-the-speed-of-jpegtran/
We commit them here due to popular demand

Thanks

### CODE REVIEW

**Comment by dcommander** [comment]
I can confirm that this speeds up progressive encoding by about 70-80% on average.  The issue is how best to integrate it.  libjpeg-turbo historically has treated the use of SIMD instruction sets as a run-time decision, so it would make the most sense to maintain that behavior for this feature as well.  I am expecting a code submission in the next few weeks that will accelerate many of the other libjpeg-turbo algorithms using AVX2 instructions.  In order to properly integrate that code, it will be necessary to develop a mechanism for detecting AVX2 support at run time, and I think it would make the most sense to borrow that detector and use it for this code as well.  It probably also makes sense to rewrite the intrinsics as NASM code (most of the compilers I use to generate "official" libjpeg-turbo binaries aren't new enough to support AVX2.)

**Comment by denji** [comment]
@dcommander https://github.com/herumi/xbyak

**Comment by mayeut** [comment]
SSE2 can be done as well with a 50-60% improvement measured (not accurately) with  `time ./jpegtran -outfile /dev/null -progressive -optimise -copy none print_poster_0025.jpg`.
Rewriting this for NASM doesn't seem trivial given the number of functions called (& most of them inlined in this C + intrinsics version)  within the loops.

**Comment by mayeut** [comment]
Seems that we can expect 90% improvement with SSE2 (same measurement method than earlier comment).
I did write non-progressive huffman coding for NASM/SSE2 (see #41). This is not as "easy" here.

**Comment by denji** [comment]
@mayeut Why not to use [yasm](https://github.com/yasm/yasm)?

**Comment by dcommander** [comment]
Obsoleted by #46

**Pull request closed without merging**
