### PR TITLE
Produce 8-bit quantization tables in 8-bit precision files

### PR DESCRIPTION
**Pull request by pornel**
As required by ISO/IEC 10918-1 B.2.4.1

### CODE REVIEW

**Comment by dcommander** [comment]
What issue does this specifically address?  Please provide exact reproduction steps.

**Comment by pornel** [comment]
A JPEG created with cjpeg with 16-bit qtables (quality low enough to overflow 255) could not be decoded with a decoder that strictly adheres to the standard: 
https://github.com/kaksmet/jpeg-decoder/issues/40

**Comment by dcommander** [comment]
This is one of those "canonical quirks" that has been present in libjpeg all along, so I am reluctant to change it.  What you're describing is well documented:

(from the `cjpeg` man page):
"(Note: quality values below about 25 generate 2-byte quantization tables, which are considered optional in the JPEG standard.  `cjpeg` emits a warning message when you give such a quality value, because some other JPEG programs may be unable to decode the resulting file.  Use `-baseline` if you need to ensure compatibility at low quality values.)"

My testing shows that this affects only JPEG files generated with quality=23 or less, which matches the description above.  Effectively, specifying `-baseline` clamps the minimum quality to whatever level is necessary to keep the qtable values at 255 or less, so you no longer really have access to all of the quality levels.  On some images I tested, that resulted in significantly larger JPEG images at around quality=10 or so.  My understanding is that `-baseline` is a convenience feature.  It keeps you from overflowing 8-bit quantization tables and ensures compatibility, but it also effectively constrains the lower end of the quality range.  I'm not going to argue that those extremely low quality levels are necessarily useful, but the fact remains that `cjpeg` has historically generated those files with 2-byte quantization tables by default.  Changing it would represent a backward incompatibility, and the usefulness of that change is highly debatable, given that `cjpeg` already provides a switch to ensure the behavior you want.  If you guys want to enable that switch by default, then that probably needs to be done downstream.

What might change my mind:
If in fact Tom Lane's assertion is false and 2-byte quantization tables are not "optional" in the JPEG spec.

Otherwise, I see no reason to change the default behavior.  As the documentation describes, applications that need to ensure conpatibility should specify `-baseline` in `cjpeg` or pass `force_baseline=TRUE` when calling one of the quality setting functions.

Note that the TurboJPEG API generates compatible files by default.  The libjpeg API itself has no default (you are required to specify whether you want to allow 2-byte quantization tables or not when you specify the JPEG quality.)  `cjpeg` defaults to allowing 2-byte quantization tables and requires you to specify `-baseline` if you don't want to allow those.

**Comment by pornel** [comment]
> If in fact Tom Lane's assertion is false and 2-byte quantization tables are not "optional" in the JPEG spec.

I think it's optional for 12-bit deep JPEGs, but not for 8-bit deep JPEGs. 

[The spec](http://www.digicamsoft.com/itu/itu-t81-44.html) says: 

> Pq: Quantization table element precision
> ­ Specifies the precision of the Q k values. Value 0 indicates 8-bit Q k values; value 1 indicates 16-bit Q k values. **Pq shall be zero for 8 bit sample precision P**

The spec doesn't have RFC-2119-like explanation how strong the meaning of *shall* is.

I see your point about change in behavior, so leaving it as-is is understandable.

**Comment by dcommander** [comment]
Yeah, libjpeg has always (literally always-- since the first release 25 years ago) had the ability to generate these incorrect JPEG files as a "feature", and cjpeg has always generated them by default.  There wasn't even a way to override this until jpeg-5.  I don't consider what the IJG is doing these days to be canonical necessarily, but it's at least a valid data point that the latest libjpeg release retains the same behavior vis-a-vis the `-baseline` switch (i.e. it also generates the incorrect JPEG files by default.)  I agree with your assessment, and I guess this is an example of incorrect behavior that has become a sort of de facto standard.

Given that the library has no default, the only real issue is cjpeg's default behavior.  An argument could be made for changing the default and introducing a switch that does the opposite of what `-baseline` does now (`-allow16bitqtable`, for instance.)  However, given that cjpeg is mainly an example program to demonstrate the features of the library, I'm not sure if it matters that much.  If this is something mozjpeg needs, then I would be OK with making the change in the evolving 1.6 code, if for no other reason than to prevent unnecessary dispersion between the code bases.

**Pull request closed without merging**
