### PR TITLE
Add x32 ABI support

### PR DESCRIPTION
**Pull request by 1camper**
x32 is a 32-bit psABI for x86-64 with 32-bit pointer size.
https://sites.google.com/site/x32abi/

### CODE REVIEW

**Comment by dcommander** [comment]
I need to know the proper copyright attribution for the new code.  That would be your name if you developed the code independently or your employer's name if you developed the code in the context of your work for them.

**Comment by dcommander** [comment]
Otherwise this looks good.  I had to revert to your initial build system approach, since the `CMAKE_C_COMPILER_ABI` variable doesn't seem to be universal.

**Comment by 1camper** [comment]
The code was developed by me personally as in the sign-off lines.

The previous ABI check seemed to break building 32-bit binaries under win64 or osx. Apparently in that case CMAKE_SYSTEM_PROCESSOR is still set to x86_64. Compiling for 32-bit x86 Linux normally changes the system string to something like i*86-{pc|unknown}-linux-{CLIB}{ABI}.
Since the x32 ABI (for now) only exists under Linux, the code would probably work correctly if a
CMAKE_SYSTEM_NAME MATCHES "Linux"
test was added to it.

**Comment by 1camper** [comment]
According to cmake git the variable CMAKE_C_COMPILER_ABI exists at least since cmake 3.0.0, while x32 detection was added with cmake 3.9.0  https://github.com/Kitware/CMake/commit/462cf254270fbd56bffc73b00dc28882fdb0bdd6#diff-8d39151f606be6bb511470242135f690. Presumably noone should want to build for x32 with outdated cmake, while building for other systems would not be broken if checking for CMAKE_C_COMPILER_ABI.

**Comment by dcommander** [comment]
Given that there are a lot of systems out there with CMake < 3.9.0 and x32 support (Ubuntu 16, for instance), I cannot presume that people will only try to build x32 binaries with the latest CMake.  Thus, relying on `CMAKE_C_COMPILER_ABI` seems like a bad idea at the moment.  I will look into the Win64 issue.

**Comment by dcommander** [comment]
Integrated in dev branch (which will eventually become libjpeg-turbo 2.1), with a couple of bug fixes, some minor formatting tweaks, and feature documentation.

**Pull request closed without merging**
