### PR TITLE
CMake: allow cross-build to iOS/tvOS/watchOS out of the box

### PR DESCRIPTION
**Pull request by SpaceIm**
This PR allows to cross-build to iOS/tvOS/watchOS "out of the box".
Currently, to build libjpeg-turbo with CMake, consumers have to inject `CMAKE_MACOSX_BUNDLE OFF`, otherwise CMake configuration fails.

By default, executables are bundles on iOS/tvOS/watchOS, and need a destination.
see https://cmake.org/cmake/help/latest/policy/CMP0006.html

Another solution would be to force `CMAKE_MACOSX_BUNDLE OFF` in CMakeLists

### CODE REVIEW

**Review by prince-chrismc — APPROVED** [review]

**Comment by dcommander** [comment]
We build libjpeg-turbo iOS packages as part of our continuous integration process, which runs every time a new commit is pushed.  Obviously iOS builds works properly, and in fact, this commit would break other types of builds.  Please be more specific about the issue you are attempting to fix and how to reproduce it.  Also, in the future, please submit an issue to discuss the matter rather than submitting an unsolicited PR.  Unsolicited PRs are almost never accepted, because they almost always break use cases that the submitter did not test.

**Comment by dcommander** [comment]
Also, @prince-chrismc, I have no idea who you are, so whether or not you approve this code is irrelevant.

**Comment by SpaceIm** [comment]
@dcommander Ok, I'll open an issue when I get some time.

**Comment by dcommander** [comment]
You don't need to open an issue.  I said "in the future", please open an issue.  At the present, I just need an explanation of the problem this PR purports to fix and how to reproduce that problem.

**Comment by SpaceIm** [comment]
Basically:
- when you set `CMAKE_SYSTEM_NAME` to iOS, CMake sets `CMAKE_MACOSX_BUNDLE` to True: https://cmake.org/cmake/help/latest/variable/CMAKE_MACOSX_BUNDLE.html
- when you run cmake with CMAKE_SYSTEM_NAME  to iOS, configuration fails because executables are BUNDLE (not RUNTIME), and they need a DESTINATION.
- It seems that your CI scripts "improperly" sets `CMAKE_SYSTEM_NAME` to Darwin for iOS (https://github.com/libjpeg-turbo/buildscripts/blob/857db0383876b45431778c2d5cb7a1250084aa95/setupscripts/iosarmv8#L14), so you don't see this issue.

Sorry I'm not on Macos right now, but I can show you the error later.

It's an issue in conan, because `CMAKE_SYSTEM_NAME` is automatically set to iOS when we build for... iOS.

**Comment by dcommander** [comment]
OK, but the solution you chose is the most intrusive possible solution.  Couldn't you have just tested for `CMAKE_SYSTEM_NAME=iOS` and set `CMAKE_MACOSX_BUNDLE` to `FALSE` in that case?  Or, better yet, couldn't you have set `CMP0006` to `old`?

Also, setting `CMAKE_SYSTEM_NAME=Darwin` for iOS builds is not "incorrect."  It was, in fact, necessary prior to CMake 3.14.

**Comment by dcommander** [comment]
I see that you edited your comment to include those suggestions.  My preference would be to simply set the policy to `old`, if that works, but setting `CMAKE_MACOSX_BUNDLE=FALSE` if `CMAKE_SYSTEM_NAME=iOS` is also acceptable (our build system will never generate iOS bundles.)

**Comment by dcommander** [comment]
I forgot that setting policies to `old` is considered deprecated.  Try this solution:
```
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -25,6 +25,11 @@ pad_number(VERSION_MINOR 3)
 pad_number(VERSION_REVISION 3)
 set(LIBJPEG_TURBO_VERSION_NUMBER ${VERSION_MAJOR}${VERSION_MINOR}${VERSION_REVISION})
 
+# Fix iOS builds with CMake 3.14 and later when CMAKE_SYSTEM_NAME=iOS
+if(CMAKE_SYSTEM_NAME STREQUAL "iOS")
+  set(CMAKE_MACOSX_BUNDLE FALSE)
+endif()
+
 string(TIMESTAMP DEFAULT_BUILD "%Y%m%d")
 set(BUILD ${DEFAULT_BUILD} CACHE STRING "Build string (default: ${DEFAULT_BUILD})")
```

**Comment by SpaceIm** [comment]
It's not sufficient, we have to test iOS, watchOS and tvOS.
I would set CMAKE_MACOSX_BUNDLE unconditionally, because anyway libjpeg-turbo CMakeLists can't work when CMAKE_MACOSX_BUNDLE is True (not without my original PR).

**Comment by SpaceIm** [comment]
Also about this PR which could break others builds, and why I say it can't:

https://cmake.org/cmake/help/latest/command/install.html#installing-targets

> For each of these arguments given, the arguments following them only apply to the target or file type specified in the argument. **If none is given, the installation properties apply to all target types**. If only one is given then only targets of that type will be installed (which can be used to install just a DLL or just an import library.)

So basically `install(TARGETS <executables targets only> DESTINATION bin)` is correct. `install(TARGETS <executables targets only> RUNTIME DESTINATION bin)` is similar but breaks if executables are BUNDLE.

**Comment by dcommander** [comment]
> So basically `install(TARGETS <executables targets only> DESTINATION bin)` is correct. `install(TARGETS <executables targets only> RUNTIME DESTINATION bin)` is similar but breaks if executables are BUNDLE.

Your patch obscures the fundamental issue.  By allowing the iOS executables to be built and installed as bundles, it would break our official iOS SDK packages when they are generated using CMake 3.14+ and later.

**Comment by SpaceIm** [comment]
I see.
Does it make sense to provide command line tools in iOS SDK package?

Anyway, what do you think of unconditional `set (CMAKE_MACOSX_BUNDLE  OFF)`?

**Comment by dcommander** [comment]
> Anyway, what do you think of unconditional `set (CMAKE_MACOSX_BUNDLE OFF)`?

I am in the process of doing exactly that if you'll leave me alone for long enough to finish and push the commit.

**Pull request closed without merging**
