### PR TITLE
Improve huffman table generation performance

### PR DESCRIPTION
**Pull request by fhanau**
Optimize the performance of jpeg_gen_optimal_table by making two changes:
1. Find the two smallest nonzero frequencies. This way only one pass over the frequency table is required for each nonzero symbol.
2. When generating the huffval array, instead of iterating over the bits and sequentially adding the symbols, iterate over the symbols directly, making sure they are written at the right location. This is achieved by keeping track of the position for the next symbol with a given number of bits in bit_pos. bit_pos is an int array instead of UINT8 for cases where there are 256 or 257 huffman symbols including the pseudo symbol – not sure if this is necessary. Overall, only one instead of 32 passes over the huffman symbols is required to construct the symbol table.

On a benchmark of mostly small images for an image optimization use case (similar to using mozjpeg's jpegtran), I see a 6% speedup, the function itself is about twice as fast. Clearly, getting even better performance is possible but would require more work for a small part of the program. The speedup for a typical libjpeg-turbo use case might be significantly smaller, let me know if you think this is not relevant for this project.

### CODE REVIEW

**Comment by fhanau** [comment]
Tested the code on an Intel i7-7700HQ. I realized that the first change should be investigated in more detail since it can be improved further (possibly to an extent that it makes sense doing it) and in its current form might not perform better (benchmarking it was inconclusive). For now, I have just benchmarked the code with the second change pertaining to filling the huffval array. I can update the pull request if you just find that part useful.
The results show that there is a noticeable speedup for 128x128 and smaller images when huffman optimization is turned on.

main branch:
```
TJ_OPTIMIZE=1 nice -n 20 ./tjbench ~/Desktop/111208_applestoregrandcentral.pnm 95 -rgb -quiet -nowrite -componly -warmup 1 -tile
Warmup time = 1.0 seconds

All performance values in Mpixels/sec

Bitmap     JPEG     JPEG  Tile   Tile    Comp    Comp    Decomp  
Format     Subsamp  Qual  Width  Height  Perf    Ratio   Perf    

RGB  (TD)  GRAY     95    8      8       3.334   1.010   N/A
RGB  (TD)  GRAY     95    16     16      9.313   2.859   N/A
RGB  (TD)  GRAY     95    32     32      23.17   5.471   N/A
RGB  (TD)  GRAY     95    64     64      45.81   7.230   N/A
RGB  (TD)  GRAY     95    128    128     71.62   7.907   N/A
RGB  (TD)  GRAY     95    256    256     90.27   8.110   N/A
RGB  (TD)  GRAY     95    512    512     98.06   8.175   N/A
RGB  (TD)  GRAY     95    1024   1024    100.8   8.184   N/A
RGB  (TD)  GRAY     95    1800   1286    102.4   8.182   N/A

RGB  (TD)  4:2:0    95    8      8       1.776   0.5807  N/A
RGB  (TD)  4:2:0    95    16     16      5.734   1.863   N/A
RGB  (TD)  4:2:0    95    32     32      14.67   4.069   N/A
RGB  (TD)  4:2:0    95    64     64      31.83   5.945   N/A
RGB  (TD)  4:2:0    95    128    128     54.61   6.782   N/A
RGB  (TD)  4:2:0    95    256    256     70.37   7.050   N/A
RGB  (TD)  4:2:0    95    512    512     78.33   7.136   N/A
RGB  (TD)  4:2:0    95    1024   1024    80.08   7.149   N/A
RGB  (TD)  4:2:0    95    1800   1286    82.54   7.148   N/A

RGB  (TD)  4:2:2    95    8      8       1.769   0.5798  N/A
RGB  (TD)  4:2:2    95    16     16      5.358   1.801   N/A
RGB  (TD)  4:2:2    95    32     32      12.82   3.827   N/A
RGB  (TD)  4:2:2    95    64     64      28.82   5.463   N/A
RGB  (TD)  4:2:2    95    128    128     48.00   6.167   N/A
RGB  (TD)  4:2:2    95    256    256     61.16   6.388   N/A
RGB  (TD)  4:2:2    95    512    512     67.01   6.459   N/A
RGB  (TD)  4:2:2    95    1024   1024    69.40   6.469   N/A
RGB  (TD)  4:2:2    95    1800   1286    70.16   6.467   N/A

RGB  (TD)  4:4:4    95    8      8       1.820   0.5818  N/A
RGB  (TD)  4:4:4    95    16     16      4.971   1.704   N/A
RGB  (TD)  4:4:4    95    32     32      12.53   3.453   N/A
RGB  (TD)  4:4:4    95    64     64      25.82   4.752   N/A
RGB  (TD)  4:4:4    95    128    128     40.47   5.275   N/A
RGB  (TD)  4:4:4    95    256    256     49.31   5.433   N/A
RGB  (TD)  4:4:4    95    512    512     52.89   5.484   N/A
RGB  (TD)  4:4:4    95    1024   1024    53.74   5.487   N/A
RGB  (TD)  4:4:4    95    1800   1286    54.48   5.483   N/A
```

Second change (populating huffval array differently) applied:
```
TJ_OPTIMIZE=1 nice -n 20 ./tjbench ~/Desktop/111208_applestoregrandcentral.pnm 95 -rgb -quiet -nowrite -componly -warmup 1 -tile

Warmup time = 1.0 seconds

All performance values in Mpixels/sec

Bitmap     JPEG     JPEG  Tile   Tile    Comp    Comp    Decomp  
Format     Subsamp  Qual  Width  Height  Perf    Ratio   Perf    

RGB  (TD)  GRAY     95    8      8       4.484   1.010   N/A
RGB  (TD)  GRAY     95    16     16      11.31   2.859   N/A
RGB  (TD)  GRAY     95    32     32      26.22   5.471   N/A
RGB  (TD)  GRAY     95    64     64      49.30   7.230   N/A
RGB  (TD)  GRAY     95    128    128     75.40   7.907   N/A
RGB  (TD)  GRAY     95    256    256     91.70   8.110   N/A
RGB  (TD)  GRAY     95    512    512     97.84   8.175   N/A
RGB  (TD)  GRAY     95    1024   1024    100.7   8.184   N/A
RGB  (TD)  GRAY     95    1800   1286    101.9   8.182   N/A

RGB  (TD)  4:2:0    95    8      8       2.438   0.5807  N/A
RGB  (TD)  4:2:0    95    16     16      7.451   1.863   N/A
RGB  (TD)  4:2:0    95    32     32      17.00   4.069   N/A
RGB  (TD)  4:2:0    95    64     64      34.73   5.945   N/A
RGB  (TD)  4:2:0    95    128    128     56.84   6.782   N/A
RGB  (TD)  4:2:0    95    256    256     72.03   7.050   N/A
RGB  (TD)  4:2:0    95    512    512     78.67   7.136   N/A
RGB  (TD)  4:2:0    95    1024   1024    81.26   7.149   N/A
RGB  (TD)  4:2:0    95    1800   1286    81.89   7.148   N/A

RGB  (TD)  4:2:2    95    8      8       2.400   0.5798  N/A
RGB  (TD)  4:2:2    95    16     16      6.698   1.801   N/A
RGB  (TD)  4:2:2    95    32     32      15.63   3.827   N/A
RGB  (TD)  4:2:2    95    64     64      31.11   5.463   N/A
RGB  (TD)  4:2:2    95    128    128     50.07   6.167   N/A
RGB  (TD)  4:2:2    95    256    256     61.51   6.388   N/A
RGB  (TD)  4:2:2    95    512    512     66.38   6.459   N/A
RGB  (TD)  4:2:2    95    1024   1024    69.54   6.469   N/A
RGB  (TD)  4:2:2    95    1800   1286    70.11   6.467   N/A

RGB  (TD)  4:4:4    95    8      8       2.488   0.5818  N/A
RGB  (TD)  4:4:4    95    16     16      5.985   1.704   N/A
RGB  (TD)  4:4:4    95    32     32      14.05   3.453   N/A
RGB  (TD)  4:4:4    95    64     64      27.52   4.752   N/A
RGB  (TD)  4:4:4    95    128    128     41.64   5.275   N/A
RGB  (TD)  4:4:4    95    256    256     46.67   5.433   N/A
RGB  (TD)  4:4:4    95    512    512     50.15   5.484   N/A
RGB  (TD)  4:4:4    95    1024   1024    53.68   5.487   N/A
RGB  (TD)  4:4:4    95    1800   1286    53.64   5.483   N/A
```

**Comment by fhanau** [comment]
I have also prepared a [second branch](https://github.com/fhanau/libjpeg-turbo/tree/huff-table-opt2) that does some more modifications building on the first change. I can clean it up and update the pull request if you think the changes are useful.
The modified code further improves performance, in particular for sizes of 256x256 or smaller, where it is 10+ % faster than the main branch. The apparent increase in performance in larger images might be spurious, there is no reason for them to be affected much as little time is spent constructing huffman tables in the first place.

huff-table-opt2 performance:
```
TJ_OPTIMIZE=1 nice -n 20 ./tjbench ~/Desktop/111208_applestoregrandcentral.pnm 95 -rgb -quiet -nowrite -componly -warmup 1 -tile
Warmup time = 1.0 seconds

All performance values in Mpixels/sec

Bitmap     JPEG     JPEG  Tile   Tile    Comp    Comp    Decomp  
Format     Subsamp  Qual  Width  Height  Perf    Ratio   Perf    

RGB  (TD)  GRAY     95    8      8       11.81   1.010   N/A
RGB  (TD)  GRAY     95    16     16      29.85   2.859   N/A
RGB  (TD)  GRAY     95    32     32      55.93   5.471   N/A
RGB  (TD)  GRAY     95    64     64      77.06   7.230   N/A
RGB  (TD)  GRAY     95    128    128     93.58   7.907   N/A
RGB  (TD)  GRAY     95    256    256     101.1   8.110   N/A
RGB  (TD)  GRAY     95    512    512     103.8   8.175   N/A
RGB  (TD)  GRAY     95    1024   1024    104.8   8.184   N/A
RGB  (TD)  GRAY     95    1800   1286    104.7   8.182   N/A

RGB  (TD)  4:2:0    95    8      8       6.242   0.5807  N/A
RGB  (TD)  4:2:0    95    16     16      19.81   1.863   N/A
RGB  (TD)  4:2:0    95    32     32      39.75   4.069   N/A
RGB  (TD)  4:2:0    95    64     64      59.51   5.945   N/A
RGB  (TD)  4:2:0    95    128    128     74.00   6.782   N/A
RGB  (TD)  4:2:0    95    256    256     81.31   7.050   N/A
RGB  (TD)  4:2:0    95    512    512     83.66   7.136   N/A
RGB  (TD)  4:2:0    95    1024   1024    84.94   7.149   N/A
RGB  (TD)  4:2:0    95    1800   1286    85.31   7.148   N/A

RGB  (TD)  4:2:2    95    8      8       6.295   0.5798  N/A
RGB  (TD)  4:2:2    95    16     16      17.77   1.801   N/A
RGB  (TD)  4:2:2    95    32     32      35.19   3.827   N/A
RGB  (TD)  4:2:2    95    64     64      51.38   5.463   N/A
RGB  (TD)  4:2:2    95    128    128     63.30   6.167   N/A
RGB  (TD)  4:2:2    95    256    256     68.90   6.388   N/A
RGB  (TD)  4:2:2    95    512    512     71.32   6.459   N/A
RGB  (TD)  4:2:2    95    1024   1024    72.29   6.469   N/A
RGB  (TD)  4:2:2    95    1800   1286    72.12   6.467   N/A

RGB  (TD)  4:4:4    95    8      8       6.527   0.5818  N/A
RGB  (TD)  4:4:4    95    16     16      16.17   1.704   N/A
RGB  (TD)  4:4:4    95    32     32      30.34   3.453   N/A
RGB  (TD)  4:4:4    95    64     64      42.96   4.752   N/A
RGB  (TD)  4:4:4    95    128    128     50.90   5.275   N/A
RGB  (TD)  4:4:4    95    256    256     54.24   5.433   N/A
RGB  (TD)  4:4:4    95    512    512     55.74   5.484   N/A
RGB  (TD)  4:4:4    95    1024   1024    55.75   5.487   N/A
RGB  (TD)  4:4:4    95    1800   1286    56.19   5.483   N/A
```

**Comment by dcommander** [comment]
Benchmarks are only useful in a relative sense, so I need to see the benchmark results both with and without the enhancement.

**Comment by fhanau** [comment]
The table for the main branch above indicates the results without the enhancement, sorry if that was unclear.

**Comment by dcommander** [comment]
The results from the second branch are compelling.  I will look into integrating the optimizations into the dev/2.2 evolving branch.

**Comment by dcommander** [comment]
Don't update the PR just yet.  I want to compare your two approaches.

**Comment by dcommander** [comment]
The second approach has been integrated into the dev branch (libjpeg-turbo 2.2 evolving.)

**Comment by fhanau** [comment]
Thank you for integrating this!
I should have mentioned this, but I later added two commits to the branch that simplify the code a bit and add some comments. It looks like the change did not improve performance further, but reduces code complexity and the comments could be useful for explaining what the changes do. Feel free to take another look if you think this could be useful.

**Comment by dcommander** [comment]
@fhanau OK, I am about to be out of the office for a week or so, but I will look at the new changes when I get back.

**Comment by dcommander** [comment]
I have integrated https://github.com/fhanau/libjpeg-turbo/commit/4d73f52032a608262f8b286dd4584836ddc73180 and https://github.com/fhanau/libjpeg-turbo/commit/184f10703eeb214177b02f88939af237267a8d66 with slight modifications.  (I changed the variable names for clarity.)  https://github.com/fhanau/libjpeg-turbo/commit/4d73f52032a608262f8b286dd4584836ddc73180 does produce measurably better performance in most cases, although not by an amount that is likely to be perceptible to an end user.

For any further improvements, please submit a new PR against the dev branch.

**Comment by fhanau** [comment]
Great, thanks for integrating the cleanup and comments!

**Pull request closed without merging**
