### PR TITLE
Add SSE2/NEON huffman encoding

### PR DESCRIPTION
**Pull request by mayeut**
Here it is in a single commit
Closes libjpeg-turbo/libjpeg-turbo#41

### CODE REVIEW

**Comment by mayeut** [comment]
Reading #3, I did all measurements with clang & gcc (clang only in #41).
In short:
clang x86: +22%
gcc x86: +17%
clang x86_64: +50%
gcc x86_64: +25%

gcc & clang now have the same performance

In details:
```
Matt$ clang --version
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
```
```
Matt$ gcc-5.2.0 --version
gcc-5.2.0 (GCC) 5.2.0
Copyright © 2015 Free Software Foundation, Inc.
```
Here's the partial output for `./tjbench ../libjpeg-turbo/testimages/vgl_6434_0018a.bmp 95 -rgb -subsamp 444 -componly`

clang x86
```
Frame rate:         3158.846814 fps
Output image size:  14225 bytes
Compression ratio:  2.409279:1
Throughput:         36.086666 Megapixels/sec
Output bit stream:  359.476767 Megabits/sec
```
clang x86 with SSE2 Huffman encoding
```
Frame rate:         3864.304367 fps
Output image size:  14225 bytes
Compression ratio:  2.409279:1
Throughput:         44.145813 Megapixels/sec
Output bit stream:  439.757837 Megabits/sec
```
gcc x86
```
Frame rate:         3259.476367 fps
Output image size:  14225 bytes
Compression ratio:  2.409279:1
Throughput:         37.236258 Megapixels/sec
Output bit stream:  370.928411 Megabits/sec
```
gcc x86 with SSE2 Huffman encoding
```
Frame rate:         3834.199553 fps
Output image size:  14225 bytes
Compression ratio:  2.409279:1
Throughput:         43.801896 Megapixels/sec
Output bit stream:  436.331909 Megabits/sec
```
clang x86_64
```
Frame rate:         3699.845454 fps
Output image size:  14225 bytes
Compression ratio:  2.409279:1
Throughput:         42.267034 Megapixels/sec
Output bit stream:  421.042413 Megabits/sec
```
clang x86_64 with SSE2 Huffman encoding
```
Frame rate:         5567.677876 fps
Output image size:  14225 bytes
Compression ratio:  2.409279:1
Throughput:         63.605152 Megapixels/sec
Output bit stream:  633.601742 Megabits/sec
```
gcc x86_64
```
Frame rate:         4439.824495 fps
Output image size:  14225 bytes
Compression ratio:  2.409279:1
Throughput:         50.720555 Megapixels/sec
Output bit stream:  505.252027 Megabits/sec
```
gcc x86_64 with SSE2 Huffman encoding
```
Frame rate:         5576.926072 fps
Output image size:  14225 bytes
Compression ratio:  2.409279:1
Throughput:         63.710803 Megapixels/sec
Output bit stream:  634.654187 Megabits/sec
```

**Comment by mayeut** [comment]
Not in a single commit anymore.
2nd commit contains correction for jsimd_none.c & NEON versions for arm/arm64

**Comment by dcommander** [comment]
I've merged the commit, with some code formatting tweaks, into a separate branch ([huffman_simd](https://github.com/libjpeg-turbo/libjpeg-turbo/tree/huffman_simd)).  However, there is unfortunately a problem.  Whereas I can reproduce a significant speedup on my Intel machine (as much as 20%, but more typically in the 5-10% range), on both of my AMD machines (an older Athlon system and a newer A10-4600M) the SIMD-accelerated Huffman routines are significantly slower than the C routines, resulting in an overall slow-down of 20-30%.  Not sure what's going on there.

**Comment by dcommander** [comment]
More information:  the 32-bit code does not seem to suffer from the afore-mentioned performance problem.  Only the 64-bit code is affected, and only on AMD processors.  I've spent all day looking at it but cannot determine what is wrong.  This code represents a risk, in the sense that it introduces significant potential for regression, and it increases the maintenance difficulties on my part (if a bug is discovered in the Huffman algorithm, now I have to debug four Huffman implementations, not just one.)  I am unwilling to accept that risk unless the code offers a significant speedup on all systems.  Please respond indicating your willingness to look into this problem, as I have no more time to look into it myself.

**Comment by mayeut** [comment]
I can only make assumptions on what's going wrong as I do only have limited hardware at my disposal for this (1 Haswell processor for x86/x64 and 1 iPhone 5S for arm/arm64).
Looking at instruction timings, seems pinsrw might be to blame here. I'll try to make a proposition without this instruction but won't be able to test this except on Haswell.
Regarding the difference between 32 & 64 bits, this seems odd. Maybe because 32bits code has too much problems with register pressure/spilling in the C code and thus, performances loss on one side is balanced by the gain on the other side (this is pure speculation). How is the performance ratio on AMD 32 bits vs Intel 32 bits ?

**Comment by dcommander** [comment]
The 32-bit SSE2 code speeds up by a lesser amount on AMD compared to Intel, but not much less (a few percent.)  I think you're probably right about pinsrw.  I'm still tinkering with it-- going to see if I can rewrite that algorithm such that it loads the block linearly from memory and then re-orders it using shuffle instructions.  If I can't make that work, however, then I'm happy to give you SSH access to one of my AMD machines so you can play with it.

**Comment by dcommander** [comment]
OK, I give up.  Please send me your SSH key offline (my e-mail address is at http://www.libjpeg-turbo.org/About/Contact), and I'll give you access to my machine.  Your Haswell machine performs similarly to mine, so I will consider this problem solved if you can produce a reasonable speedup on the AMD machine without compromising the speedup on the Haswell machine.

**Comment by mayeut** [comment]
Here's what I could do on the AMD system without much changes (seems not affect Intel).
The bottleneck doesn't seem to be `pinrw`. It's somewhere in the loop.
I tried this on different levels of quality since low quality doesn't benefit from this much.

```
Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz

master Apple LLVM version 7.0.2 (clang-700.1.81)
vgl_6434_0018a.bmp 10 96.175781 Megapixels/sec
vgl_6434_0018a.bmp 50 79.081449 Megapixels/sec
vgl_6434_0018a.bmp 95 40.375936 Megapixels/sec
artificial.ppm 10 126.865651 Megapixels/sec
artificial.ppm 50 121.265775 Megapixels/sec
artificial.ppm 95 98.719830 Megapixels/sec
nightshot_iso_100.ppm 10 125.099283 Megapixels/sec
nightshot_iso_100.ppm 50 118.560313 Megapixels/sec
nightshot_iso_100.ppm 95 86.287249 Megapixels/sec

master gcc 5.2.0
vgl_6434_0018a.bmp 10 117.405613 Megapixels/sec
vgl_6434_0018a.bmp 50 107.113484 Megapixels/sec
vgl_6434_0018a.bmp 95 49.273572 Megapixels/sec
artificial.ppm 10 164.411968 Megapixels/sec
artificial.ppm 50 144.341106 Megapixels/sec
artificial.ppm 95 121.644427 Megapixels/sec
nightshot_iso_100.ppm 10 165.034828 Megapixels/sec
nightshot_iso_100.ppm 50 155.017617 Megapixels/sec
nightshot_iso_100.ppm 95 106.943637 Megapixels/sec

sse2 Apple LLVM version 7.0.2 (clang-700.1.81)
vgl_6434_0018a.bmp 10 124.989567 Megapixels/sec
vgl_6434_0018a.bmp 50 102.293836 Megapixels/sec
vgl_6434_0018a.bmp 95 60.283614 Megapixels/sec
artificial.ppm 10 156.770232 Megapixels/sec
artificial.ppm 50 147.979058 Megapixels/sec
artificial.ppm 95 126.266599 Megapixels/sec
nightshot_iso_100.ppm 10 163.327363 Megapixels/sec
nightshot_iso_100.ppm 50 160.293536 Megapixels/sec
nightshot_iso_100.ppm 95 119.749912 Megapixels/sec
```

```
AMD A10-4600M

master gcc 4.4.7
vgl_6434_0018a.bmp 10 87.601425 Megapixels/sec
vgl_6434_0018a.bmp 50 70.512408 Megapixels/sec
vgl_6434_0018a.bmp 95 38.734824 Megapixels/sec
artificial.ppm 10 117.816808 Megapixels/sec
artificial.ppm 50 111.528974 Megapixels/sec
artificial.ppm 95 93.695654 Megapixels/sec
nightshot_iso_100.ppm 10 118.292189 Megapixels/sec
nightshot_iso_100.ppm 50 113.852624 Megapixels/sec
nightshot_iso_100.ppm 95 83.349448 Megapixels/sec

SSE2 gcc 4.4.7
vgl_6434_0018a.bmp 10 86.149083 Megapixels/sec
vgl_6434_0018a.bmp 50 71.778322 Megapixels/sec
vgl_6434_0018a.bmp 95 41.334041 Megapixels/sec
artificial.ppm 10 115.161780 Megapixels/sec
artificial.ppm 50 109.470484 Megapixels/sec
artificial.ppm 95 94.887492 Megapixels/sec
nightshot_iso_100.ppm 10 117.027975 Megapixels/sec
nightshot_iso_100.ppm 50 109.886765 Megapixels/sec
nightshot_iso_100.ppm 95 85.806819 Megapixels/sec
```

**Comment by ssvb** [comment]
> The bottleneck doesn't seem to be pinsrw. It's somewhere in the loop.

Looking at the changes in your patch, the ``BSR`` instruction indeed might be the likely culprit. It appears to be almost universally bad on AMD processors (takes ~10 cycles) and also on Intel Atom according to the cycle timings from http://www.agner.org/optimize/instruction_tables.pdf

Maybe it makes sense to have two implementations (with and without ``BSR``) and select a better one at runtime via the use of ``CPUID`` in the assembly code (something like a ``bsr_is_fast()`` function) or  use ``__builtin_cpu_is()`` intrinsic if compiled by GCC?

There are various tricks to optimize the counting leading zeros operation (unless the code can be changed to not require it at all): http://graphics.stanford.edu/~seander/bithacks.html#IntegerLogLookup

**Comment by ssvb** [comment]
> There are various tricks to optimize the counting leading zeros operation (unless the code can be changed to not require it at all): http://graphics.stanford.edu/~seander/bithacks.html#IntegerLogLookup

Well, there is even no need to invent anything. The slow microcoded ``BSR`` can be replaced with a ``jpeg_nbits_table`` lookup (just like libjpeg was always able to do).

**Comment by dcommander** [comment]
The new patch went a long way toward solving the problem.  I'm going to do some further experiments.

**Comment by dcommander** [comment]
[huffman_simd](https://github.com/libjpeg-turbo/libjpeg-turbo/tree/huffman_simd) contains a new commit that should resolve the performance issue on newer AMD chips.  The NASM code now uses a precomputed bit table, which matches the behavior of the C code on x86 platforms.  This avoids the slow bsr instruction on certain x86 platforms.

This has no significant effect on the performance for Intel chips, but the effect for AMD chips is dramatic.  On my old Athlon64, the SSE2 code was brought up to parity with the C code (give or take 5%), and on the newer AMD APU, the SSE2 code now enjoys roughly the same speedup relative to C as it does on Intel.

I think I can extract some additional performance on x86-64 by restructuring the k loop, thus avoiding the bsf instruction (which is also probably slow.)

**Comment by mayeut** [comment]
Seems we did the same thing. I didn't have time to test it on AMD though.
I changed my code to use a 32k LUT (Since only using it to lookup absolute values, there only might be a problem for -32768 == abs(-32768) which shall not happen). Seems to be a speedup even on Intel. Might be good to use the existing LUT as you said.
Regarding the `BSF` instruction, I tried using the `TZCNT` which is, in theory, much faster on AMD chips but in fact, the loop refactoring using `TZCNT` was slower on AMD and roughly the same on Intel.

**Comment by mayeut** [comment]
Seems removing `BSF` on Intel has a really bad impact on performances.
@dcommander, seems you have this one almost figured out. If you still need some help with it, don't hesitate to ask, otherwise, I'll now focus on getting something for #25. I already prepared something in intrinsics that shows promising, also on your AMD system. I will now port this to assembly & open a new PR.

**Comment by dcommander** [comment]
You're right about bsf.  I tried two different approaches to improve performance:

1. I kept the existing kloop_prepare macro, but rather than store the processed coefficients to the stack and pull them out of the stack in the k loop, I used all 15 SSE2 registers to store the coefficients, then I pulled from those SSE2 registers one word at a time in the k loop.  In order to make this work, however, I had to restructure the k loop similarly to the C code-- i.e. implement it as a macro that accepts static parameters telling it where it can find the coefficient for each iteration.

2. In kloop_prepare, I moved the coefficients into xmm0-xmm7 without reordering, then I used pextrw within the k loop to process the coefficients in the correct (zigzag) order.  This also required refactoring the k loop as a macro.

Apparently implementing the k loop as a macro and unrolling it is a bad idea in this case, because it prevents the loop from skipping ahead if it encounters a block of zeroes.

**Comment by dcommander** [comment]
Well, I tried for literally hours and could not figure out (or find information regarding) how to access a C array from within a NASM function-- and of course the way it should work (replacing the local declaration of jpeg_nbits_table with "extern jpeg_nbits_table" and making the table in jpeg_nbits_table.h global instead of static) caused a segfault.  No clue, and I'm not sure if I care enough about saving 64 kbytes of memory to continue beating my head against the wall about it.

**Comment by dcommander** [comment]
ARGH!  Well, it's unfortunately not as simple as just leaving things the way they are, because unfortunately the existing code doesn't compile without PIC:

      CCLD     libjpeg.la
    /usr/bin/ld: .libs/jcapimin.o: relocation R_X86_64_32 against `a local symbol' can not be used when making a shared object; recompile with -fPIC

If there's any way you could look into that, I would appreciate it.  I've spent hours and can find nothing that solves this problem-- which I suspect is the same problem as my inability to reuse the C table.  At the moment, I do not have enough money in the bank to pay this month's bills.  I want to see through the x86 part of the project, but I will need to secure funding before I can even touch the NEON stuff.

**Comment by mayeut** [comment]
I will try to get this solve. I'll keep you posted.

**Comment by dcommander** [comment]
Stand by.  It appears that the non-PIC compilation problem exists regardless of the presence of the jchuff SIMD extension.  I'm trying to pinpoint where the regression occurred.

**Comment by dcommander** [comment]
This was my stupidity, and I apologize for the noise.  I was trying to build with `--without-pic`, but you can't do that without also specifying `--disable-shared`.

**Comment by mayeut** [comment]
Not looking into it then.

**Comment by dcommander** [comment]
The final version of SSE2 Huffman encoding has been pushed to master.  Thanks again for all of your hard work on this.

**Comment by mayeut** [comment]
You're welcome. I will open a new PR for NEON in sync with master in order not to lose this work. There's a bug in the ARMv7 version anyway so it needs more work.

**Pull request closed without merging**
