### PR TITLE
Arm AArch64 intrinsics compression optimizations

### PR DESCRIPTION
**Pull request by jwright-arm**
These two patches give a combined 0-4% overall speedup for JPEG compression on AArch64 - depending on the compiler used and the type of core used for testing.

See the attached spreadsheet containing benchmark numbers showing the performance impact when using Clang releases 6-13 and builds of Clang and GCC tip of tree.

[libjpegturbo-armintrinsics-opts.ods](https://github.com/libjpeg-turbo/libjpeg-turbo/files/7807336/libjpegturbo-armintrinsics-opts.ods)

### CODE REVIEW

**Comment by dcommander** [comment]
The `#pragma` commit is innocuous, but for the Huffman coding commit, I will need to re-run some of the benchmarks I ran for the initial Neon intrinsics implementation in 2.1 beta1.  Since we've established that my equipment sometimes exhibits performance regressions that your equipment does not, I unfortunately cannot take your benchmark results at face value.  Given that the labor necessary to re-run the benchmarks is significant, the speedup is not very great (probably imperceptible to the end user), and our project funding for this year is very limited, I am unwilling to spend any of the general fund on this.  If Arm is willing to pay for my labor to benchmark these commits to my satisfaction, then I'm happy to integrate this PR.  Otherwise it will have to wait.

**Comment by jwright-arm** [comment]
That's fair enough, we'll wait - it's not a massive boost by any means and I agree that benchmarking this stuff is very hard on devices that are not actively cooled. (The N1 SDP numbers are much more stable than those from the Pixel 6 - the N1 SDP is actively cooled and sits in a climate controlled lab but the phone sits on my desk in my house due to WFH...)

On the discrepancies that we saw before: I think my numbers may have been wrong - the device has been playing up a bit recently (probably sat in the farm for too long and needs to be retired) but I'm still trying to get to the bottom of it to get a definitive answer.

On a slightly different note, I've done a compiler performance comparison with libjpeg-turbo using cores in the Pixel 6 and the N1 SDP and the graphs make for interesting reading. I'll drop you an email with it attached.

**Comment by dcommander** [comment]
Yes, on my Rock960 board, the performance is stable for the Cortex-A53 cores as long as I disable CPU scaling, but performance still fluctuates for the Cortex-A72 cores, so it takes a lot of babysitting to ensure that I can get proper results from those cores.

**Comment by dcommander** [comment]
Questions about the `#pragma unroll` commit:
1. Doesn't `-O3` take care of that already?
2. Why can't we just manually unroll the loop and avoid the Clang-specific `#pragma`?  `DCTSIZE` is always 8.

**Comment by dcommander** [comment]
I haven't done a comprehensive test with multiple compilers, but with Clang 10 at least, the `#pragma` does not change the generated assembly code.

**Comment by jwright-arm** [comment]
Historically, Clang has been a bit over zealous with loop unrolling. Over the last few years it has been reined in (regardless of optimization level) and we see the first effects of this on our quantization code with [Clang 11.0.1](https://godbolt.org/z/rv8Kjz5r9). Releases for Clang 12 and 13 are not available in Compiler Explorer but I have verified that the loop is not unrolled with these compilers either; nor is it unrolled with [Clang tip of tree](https://godbolt.org/z/v3PjbP6vf).

The loop is unrolled (as in Clang 10.x.x) for all of the aforementioned compilers when the `#pragma` is in place.

What don't we just unroll the loop in source code? This code is used for AArch32 and AArch64 targets. AArch32 has half the number of Neon registers and unrolling the loop causes spilling to the stack. (Note the guards on AArch64 in the patch adding the `#pragma`.)

**Comment by dcommander** [comment]
Can you explain more about the register pressure issue with AArch32? It seems to me that manually unrolling would cause the code to use fewer registers, since the intrinsics arguments would all be constant.

**Comment by jwright-arm** [comment]
I don't follow you. We're short of Neon SIMD registers if we unroll, not general purpose ones. (At least when using the `#pragma` to do the unrolling.)

The `#pragma` is the easy solution for AArch64. If unrolled, the working set of Neon registers seems to be just too large for AArch32 - large enough, at least, for  both [GCC and Clang to spill to the stack](https://godbolt.org/z/4T3q37xK7). It may be possible to curate an unrolled implementation in assembly that does not spill for AArch32, but I won't be allowed to spend time looking into that. If you're going to try in source code, you're at the mercy of the compilers.

**Comment by dcommander** [comment]
OK, but why does unrolling cause more Neon registers to be used?  That's what I don't understand.

**Comment by jwright-arm** [comment]
Unrolling here means that we have twice as much data to work with - significantly more than can fit in 16 128-bit registers if each piece of data got its own architectural register. However, we don't need access to all of the data at all times in the function. The compiler attempts to out the live-range for each piece of data and then assigns architectural registers appropriately. If the compiler thinks there are more overlapping live ranges than there are architectural registers, it has to spill to the stack. (This is a bit of an over simplification.)

If it can execute one iteration of this loop (operating on half of the block) without spilling, it 'should' be able to execute the unrolled loop by naively serializing the two iterations - and perhaps doing a bit of interleaving to hide load/store latency. Either the compiler gets confused and messes up register allocation somewhere (likely), or it thinks it can 'hide' the spills by executing them where the data isn't needed and it hasn't got any other instructions immediately available in the schedule (unlikely).

**Comment by dcommander** [comment]
Ugh.  And people wonder why I am hesitant to use compiler intrinsics...

I was able to make Clang behave by loading the data on a just-in-time basis:
```
#include <arm_neon.h>

#define JCOEFPTR int16_t*
#define DCTSIZE 8
#define DCTSIZE2 64
#define DCTELEM int16_t
#define UDCTELEM uint16_t

void jsimd_quantize_neon(JCOEFPTR coef_block, DCTELEM *divisors,
                         DCTELEM *workspace)
{
  JCOEFPTR out_ptr = coef_block;
  UDCTELEM *recip_ptr = (UDCTELEM *)divisors;
  UDCTELEM *corr_ptr = (UDCTELEM *)divisors + DCTSIZE2;
  DCTELEM *shift_ptr = divisors + 3 * DCTSIZE2;
  int i;

  int16x8_t row0, row1, row2, row3, shift0, shift1, shift2, shift3,
    sign_row0, sign_row1, sign_row2, sign_row3;
  uint16x8_t recip0, recip1, recip2, recip3, corr0, corr1, corr2, corr3,
    abs_row0, abs_row1, abs_row2, abs_row3;
  int32x4_t row0_l, row0_h, row1_l, row1_h, row2_l, row2_h, row3_l, row3_h;

#define LOOP(i) \
  /* Load DCT coefficients. */ \
  row0 = vld1q_s16(workspace + (i + 0) * DCTSIZE); \
  row1 = vld1q_s16(workspace + (i + 1) * DCTSIZE); \
  row2 = vld1q_s16(workspace + (i + 2) * DCTSIZE); \
  row3 = vld1q_s16(workspace + (i + 3) * DCTSIZE); \
  \
  /* Extract sign from coefficients. */ \
  sign_row0 = vshrq_n_s16(row0, 15); \
  sign_row1 = vshrq_n_s16(row1, 15); \
  sign_row2 = vshrq_n_s16(row2, 15); \
  sign_row3 = vshrq_n_s16(row3, 15); \
  /* Get absolute value of DCT coefficients. */ \
  abs_row0 = vreinterpretq_u16_s16(vabsq_s16(row0)); \
  abs_row1 = vreinterpretq_u16_s16(vabsq_s16(row1)); \
  abs_row2 = vreinterpretq_u16_s16(vabsq_s16(row2)); \
  abs_row3 = vreinterpretq_u16_s16(vabsq_s16(row3)); \
  \
  /* Load reciprocals of quantization values. */ \
  recip0 = vld1q_u16(recip_ptr + (i + 0) * DCTSIZE); \
  recip1 = vld1q_u16(recip_ptr + (i + 1) * DCTSIZE); \
  recip2 = vld1q_u16(recip_ptr + (i + 2) * DCTSIZE); \
  recip3 = vld1q_u16(recip_ptr + (i + 3) * DCTSIZE); \
  \
  /* Multiply DCT coefficients by quantization reciprocals. */ \
  row0_l = vreinterpretq_s32_u32(vmull_u16(vget_low_u16(abs_row0), \
                                           vget_low_u16(recip0))); \
  row0_h = vreinterpretq_s32_u32(vmull_u16(vget_high_u16(abs_row0), \
                                           vget_high_u16(recip0))); \
  row1_l = vreinterpretq_s32_u32(vmull_u16(vget_low_u16(abs_row1), \
                                           vget_low_u16(recip1))); \
  row1_h = vreinterpretq_s32_u32(vmull_u16(vget_high_u16(abs_row1), \
                                           vget_high_u16(recip1))); \
  row2_l = vreinterpretq_s32_u32(vmull_u16(vget_low_u16(abs_row2), \
                                           vget_low_u16(recip2))); \
  row2_h = vreinterpretq_s32_u32(vmull_u16(vget_high_u16(abs_row2), \
                                           vget_high_u16(recip2))); \
  row3_l = vreinterpretq_s32_u32(vmull_u16(vget_low_u16(abs_row3), \
                                           vget_low_u16(recip3))); \
  row3_h = vreinterpretq_s32_u32(vmull_u16(vget_high_u16(abs_row3), \
                                           vget_high_u16(recip3))); \
  \
  corr0 = vld1q_u16(corr_ptr + (i + 0) * DCTSIZE); \
  corr1 = vld1q_u16(corr_ptr + (i + 1) * DCTSIZE); \
  corr2 = vld1q_u16(corr_ptr + (i + 2) * DCTSIZE); \
  corr3 = vld1q_u16(corr_ptr + (i + 3) * DCTSIZE); \
  \
  /* Add correction. */ \
  abs_row0 = vaddq_u16(abs_row0, corr0); \
  abs_row1 = vaddq_u16(abs_row1, corr1); \
  abs_row2 = vaddq_u16(abs_row2, corr2); \
  abs_row3 = vaddq_u16(abs_row3, corr3); \
  \
  /* Narrow back to 16-bit. */ \
  row0 = vcombine_s16(vshrn_n_s32(row0_l, 16), vshrn_n_s32(row0_h, 16)); \
  row1 = vcombine_s16(vshrn_n_s32(row1_l, 16), vshrn_n_s32(row1_h, 16)); \
  row2 = vcombine_s16(vshrn_n_s32(row2_l, 16), vshrn_n_s32(row2_h, 16)); \
  row3 = vcombine_s16(vshrn_n_s32(row3_l, 16), vshrn_n_s32(row3_h, 16)); \
  \
  /* Since VSHR only supports an immediate as its second argument, negate the \
   * shift value and shift left. \
   */ \
  shift0 = vld1q_s16(shift_ptr + (i + 0) * DCTSIZE); \
  shift1 = vld1q_s16(shift_ptr + (i + 1) * DCTSIZE); \
  shift2 = vld1q_s16(shift_ptr + (i + 2) * DCTSIZE); \
  shift3 = vld1q_s16(shift_ptr + (i + 3) * DCTSIZE); \
  \
  row0 = vreinterpretq_s16_u16(vshlq_u16(vreinterpretq_u16_s16(row0), \
                                         vnegq_s16(shift0))); \
  row1 = vreinterpretq_s16_u16(vshlq_u16(vreinterpretq_u16_s16(row1), \
                                         vnegq_s16(shift1))); \
  row2 = vreinterpretq_s16_u16(vshlq_u16(vreinterpretq_u16_s16(row2), \
                                         vnegq_s16(shift2))); \
  row3 = vreinterpretq_s16_u16(vshlq_u16(vreinterpretq_u16_s16(row3), \
                                         vnegq_s16(shift3))); \
  \
  /* Restore sign to original product. */ \
  row0 = veorq_s16(row0, sign_row0); \
  row0 = vsubq_s16(row0, sign_row0); \
  row1 = veorq_s16(row1, sign_row1); \
  row1 = vsubq_s16(row1, sign_row1); \
  row2 = veorq_s16(row2, sign_row2); \
  row2 = vsubq_s16(row2, sign_row2); \
  row3 = veorq_s16(row3, sign_row3); \
  row3 = vsubq_s16(row3, sign_row3); \
  \
  /* Store quantized coefficients to memory. */ \
  vst1q_s16(out_ptr + (i + 0) * DCTSIZE, row0); \
  vst1q_s16(out_ptr + (i + 1) * DCTSIZE, row1); \
  vst1q_s16(out_ptr + (i + 2) * DCTSIZE, row2); \
  vst1q_s16(out_ptr + (i + 3) * DCTSIZE, row3);

  LOOP(0)
  LOOP(DCTSIZE / 2)
}
```
Whether or not that results in better performance is an open question.  It would depend on how the computations interleave with I/O.  I can say, however, that the code above results in fewer instructions than `#pragma unroll` for all of the test cases in the matrix { {AArch32, AArch64}, {GCC, Clang} }.  Since I don't have time to benchmark it, I will integrate `#pragma unroll` for now, since I now have enough information to justify that solution.

**Pull request closed without merging**
