### PR TITLE
MIPS64 SIMD: Rename from loongson

### PR DESCRIPTION
**Pull request by FlyGoat**
This commit renamed loongson simd to mips64 simd and add runtime
detection for MMI Intrinsics.

### CODE REVIEW

**Comment by dcommander** [comment]
This looks good, and I don't see any reason why it can't be integrated along with the MSA enhancements.  One question:

Previously, it was not necessary to pass any flags to the compiler when I built MMI code on the test machine that Loongson provided (last January, in the context of integrating #306.)  This patch, however, passes `-mloongson-mmi,-mloongson-ext` to the assembler when building the MMI code.  Can you explain the difference?

**Comment by FlyGoat** [comment]
> This looks good, and I don't see any reason why it can't be integrated along with the MSA enhancements. One question:
> 
> Previously, it was not necessary to pass any flags to the compiler when I built MMI code on the test machine that Loongson provided (last January, in the context of integrating #306.) This patch, however, passes `-mloongson-mmi,-mloongson-ext` to the assembler when building the MMI code. Can you explain the difference?

The toolchain provided by Loongson had defaulted their march=loongson3a, But generic MIPS64 toolchain won't accept MMI instructions unless we set these flags. And these flags have no side affects on Loongson toolchain.

**Comment by dcommander** [comment]
Perfect.  I'll make sure this gets into 2.1.

**Comment by dcommander** [comment]
Integrated into dev, with some changes.  Among those changes was re-using the /proc/cpuinfo parsing code from existing SIMD extensions.

@FlyGoat @zhanglixia-hf Please retest the dev branch to ensure that it still works properly.  I do not have a Loongson machine for testing.

**Comment by wzssyqa** [comment]
I don't think that we should rename it， since it is Loongson only INSNs.

**Comment by dcommander** [comment]
@wzssyqa Eventually MSA instructions will be added to the simd/mips64/ folder (refer to #377.)  MMI instructions are supported in GCC now, so the main purpose of this PR is to allow those instructions to be detected automatically at configure time and run time when using non-Loongson-specific compilers.  Thus, it is conceivable that a MIPS64 build of libjpeg-turbo could support both MMI and MSA with the same binary.  That is the correct approach when the same underlying CPU architecture supports multiple SIMD instruction sets.  For instance, not all x86 chips support AVX2 instructions, but all x86 builds of libjpeg-turbo have the ability to use AVX2 instructions.  This is much the same situation.  The only difference is that MMI instructions are limited to Loongson CPUs, but as long as those CPUs are otherwise MIPS64-compatible, then SIMD extensions for them belong in the same place as SIMD extensions for other MIPS64-compatible CPUs.  I am open to introducing new CMake variables that allow specific SIMD instruction sets from being excluded from the build, if building for a platform that supports multiple SIMD instruction sets.

**Comment by wzssyqa** [comment]
Sorry. I misunderstood it.

It seems that we can use getauxval to get whether MSA is useable. I will have a try it.

**Comment by wzssyqa** [comment]
`#include <sys/auxv.h>
#include <asm/hwcap.h>
#include <stdio.h>

int main(){
        unsigned long aux = getauxval(AT_HWCAP);
        if (aux & HWCAP_MIPS_MSA)
                printf("MSA is usable\n");
}`

With this we can determine whether MSA is usable.

**Comment by FlyGoat** [comment]
I'm going to test it tomorrow~
Thanks

**Comment by FlyGoat** [comment]
Sorry for the delay.
It works.
Thanks.

**Pull request closed without merging**
