### PR TITLE
Small optimizations

### PR DESCRIPTION
**Pull request by Shark64**
I've noticed that the routine to check the CPU features uses the full 64bit regs even if cpuid and xgetbv only write to the lower 32bits. We can use 32 bit registers and save some code size. 
Also in jsimd_convsamp_avx2() some legacy SSE instruction are mixed with VEX-coded AVX ones. I've switched all of them to VEX encoding to avoid any transition penality with the dirty upper state of ymm registers

### CODE REVIEW

**Comment by dcommander** [comment]
How much code size is saved by your modifications to jsimdcpu.asm?  If it's not more than a few bytes, then I'm not interested.

Regarding the use of VEX versions of SSE instructions, please indicate how much performance increase you have observed from this.  I've personally analyzed the AVX2 code using the Intel SDE (https://software.intel.com/en-us/articles/avoiding-avx-sse-transition-penalties), and it didn't detect any transition penalties in jquanti-avx2.asm.  Furthermore, that's not the only place in the AVX2 code in which movq is used.

In general, I am interested in fixes for user-visible issues, not for hypothetical issues.

**Comment by Shark64** [comment]
The reduction of size in jsimdcpu.asm is quite significant for such a small file, almost 40%. More importantly while practically all x86 cpu can recognize xor eax eax and similar as a zero idiom during renaming, some (like silvermont) fail to do that if you use the REX-prefix so there's no reason to pad the instructions with unnecessary byte extensions.

The reason why i switched the SSE instruction to VEX is that with it the instruction lenght is 1 byte shorter than the original encoding, it's not a huge gain in performance by any means but there's no reason to keep them legacy encoded in a routine that already uses VEX prefix for SIMD instructions

**Comment by dcommander** [comment]
> The reduction of size in jsimdcpu.asm is quite significant for such a small file, almost 40%.

That's meaningless without knowing how many total bytes are involved.  A 40% reduction from 5 bytes to 3 is hardly noteworthy, for instance.

> More importantly while practically all x86 cpu can recognize xor eax eax and similar as a zero idiom during renaming, some (like silvermont) fail to do that if you use the REX-prefix so there's no reason to pad the instructions with unnecessary byte extensions.

So what would be the worst case on Silvermont?  Would the CPU detection fail?

> 
> The reason why i switched the SSE instruction to VEX is that with it the instruction lenght is 1 byte shorter than the original encoding, it's not a huge gain in performance by any means but there's no reason to keep them legacy encoded in a routine that already uses VEX prefix for SIMD instructions

OK, but those aren't the only places in which those instructions are used.  I need to understand:
* What made you focus on only the SSE instructions in `jsimd_convsamp_avx2()` when movq is used elsewhere
* What made you focus on only the 64-bit code when those same instructions are used in the 32-bit code as well
* Why Intel SDE doesn't detect any transition penalty

**Comment by Shark64** [comment]
> > The reduction of size in jsimdcpu.asm is quite significant for such a small file, almost 40%.
> 
> That's meaningless without knowing how many total bytes are involved. A 40% reduction from 5 bytes to 3 is hardly noteworthy, for instance.
> 
> > More importantly while practically all x86 cpu can recognize xor eax eax and similar as a zero idiom during renaming, some (like silvermont) fail to do that if you use the REX-prefix so there's no reason to pad the instructions with unnecessary byte extensions.
> 
> So what would be the worst case on Silvermont? Would the CPU detection fail?

No, from a functionality point of view it wuold work on Silvermont too. I agree that it's a small issue but if you can have the same functionality with less code (and the patch is basically trivial) i don't see any reason to keep the longer code, even if it's not something that the user will notice. CPUID is defined with 32bit outputs by Intel, why use 64bit when the upper 32 are guaranteed to be always zero?
> 
> > The reason why i switched the SSE instruction to VEX is that with it the instruction lenght is 1 byte shorter than the original encoding, it's not a huge gain in performance by any means but there's no reason to keep them legacy encoded in a routine that already uses VEX prefix for SIMD instructions
> 
> OK, but those aren't the only places in which those instructions are used. I need to understand:
> 
>     * What made you focus on only the SSE instructions in `jsimd_convsamp_avx2()` when movq is used elsewhere
> 
>     * What made you focus on only the 64-bit code when those same instructions are used in the 32-bit code as well
> 
>     * Why Intel SDE doesn't detect any transition penalty
Sure, the reason i focused only on jsimd_convsamp_avx2() is that I thought would be easier to do a pull request for each separate issue. If you prefer to have them batched together i can make a pull request with all the movq -> vmovq patches in a single pull.

I didn't look at the 32bit code because, if you're using a CPU with AVX, there's no reason to run on IA32 mode. x86-64 is still ugly enough without the 8 registers only&parameters on stack restrictions that you get with the original x86 :D 

I think that SDE doesn't detect any transition penalty because all the surrouding instructions are VEX coded, the upper 128bits are architecturally defined as zero. Still the opcode is shorter and i think the code will be more "future proof" if all the SSE instructions within the *avx2 files are re-ecoded as AVX.128

**Comment by dcommander** [comment]
Unfortunately nothing is ever trivial when it comes to this code base.  I can certainly appreciate your desire to clean it up a bit, but from a project management point of view, this is code that affects millions of people.  With a project of this scope, with as many touch points as it has throughout the OSS community, the default answer always has to be "do nothing."  You said that you could see no reason to keep the existing code, but the reason is:  the existing code is well-tested, whereas your proposed modifications to it are not.  Thus, I would not feel comfortable checking this in without testing it for regressions (including performance regressions) on several different platforms and putting it through a beta cycle.  It simply isn't worth it to devote the time necessary to do that unless there is a clear advantage to your approach vs. the existing approach.  I will reconsider if you can demonstrate such an advantage.

**Comment by dcommander** [comment]
NOTE:  that advantage need not necessarily be user-visible.  I would be satisfied with some utility, like SDE, saying that your code experiences fewer transitions or whatnot.  But absent such concrete evidence of the advantages of your approach, this PR is purely academic.

**Pull request closed without merging**
