### PR TITLE
Add option to override CPU_TYPE detection

### PR DESCRIPTION
**Pull request by hugolm84**
Hi! 

My  `CMAKE_SYSTEM_PROCESSOR` is parsed as `cortexa9t2hf-neon-poky`  which is not considered to be an ARM processor according to the CMakeLists.txt. This allows users that know that the processor is an ARM type to override the internal detection. Use `-DCPU_TPYE=arm` to specify ARM processor for example. Of course, a user can specify any of the supported processor names.

### CODE REVIEW

**Comment by dcommander** [comment]
What type of processor are you using, and what O/S?

**Comment by hugolm84** [comment]
I am cross compiling on a Linux host for an cortex a-9 using the arm-poky toolset from Yocto.

**Comment by dcommander** [comment]
If you are cross-compiling, then why can’t you set `CMAKE_SYSTEM_PROCESSOR` in your toolchain file?

**Comment by hugolm84** [comment]
Ooops! Im sorry, forgive me for wasting you time!

**Pull request closed without merging**
