### PR TITLE
Build: Add a CMake Package config install

### PR DESCRIPTION
**Pull request by hjmallon**
Relates to https://github.com/libjpeg-turbo/libjpeg-turbo/issues/339

### CODE REVIEW

**Comment by dcommander** [comment]
I misunderstood this to be more similar to pkg-config, whereby a single file is generated with information about where to find the link libraries and include files.  The files generated by this patch seem rather complex and fragile.  Specifically:

1. **libjpeg-turboTargets.cmake** depends on the build targets, which are internal to the build system and should never be exposed to an end user.
2. **libjpeg-turboTargets-release.cmake** depends on the build type, which again should never be exposed to an end user.  I'm also not quite sure why this file is installed, since it doesn't appear to be used.

Also, I need to understand:

1. How a downstream build system would use this config file
2. Why you added `INCLUDES DESTINATION` to install targets that do not install any header files
3. Whether the libjpeg-turboTargets.cmake file is even necessary and what function it serves for downstream users
4. What function the libjpeg-turboConfigVersion.cmake file serves

My preference, if possible, would be to have one file named libjpeg-turbo-config.cmake (not libjpeg-turboConfig.cmake) that is installed under `${CMAKE_INSTALL_LIBDIR}/cmake` (not `${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}`), but if there is a good reason why that isn't a good idea, then please let me know.

**Comment by hjmallon** [comment]
> libjpeg-turboTargets.cmake depends on the build targets, which are internal to the build system and should never be exposed to an end user.

If this is the case then the config file should exist downstream of here. This is a way to link the library (represented by build targets) in CMake of another project (see example below).

> libjpeg-turboTargets-release.cmake depends on the build type, which again should never be exposed to an end user. I'm also not quite sure why this file is installed, since it doesn't appear to be used.

This file is included by `libjpeg-turboTargets.cmake` see the line`file(GLOB CONFIG_FILES "${_DIR}/libjpeg-turboTargets-*.cmake")` and its surrounding lines. The reason why it depends on build type is to allow an install of Release and Debug targets side by side (e.g. using a 'd' suffix on the names or in a '/dbg/' folder. In this way the below example could create a Window Visual Studio Project for `foo` where the Debug type linked a Debug libjpeg-turbo and the Release type linked Release.

> How a downstream build system would use this config file

In the downstream CMakeLists.txt you can use something like
```cmake
# Collects info on installed libjpeg-turbo and adds to IMPORT targets
find_package(libjpeg-turbo CONFIG REQUIRED)

add_executable(foo foo.cpp)

# This adds all the requires include and link paths to the target
target_link_libraries(foo PUBLIC libjpeg-turbo::jpeg)
```

> Why you added INCLUDES DESTINATION to install targets that do not install any header files

This means that `target_link_libraries(foo PUBLIC libjpeg-turbo::jpeg)` will also add the correct include path for the library (in this case `${INSTALL_PREFIX}/include`) to the target that links it. You can see them in the `libjpeg-turboTargets.cmake` file as `INTERFACE_INCLUDE_DIRECTORIES`.

> Whether the libjpeg-turboTargets.cmake file is even necessary and what function it serves for downstream users

It exports the installed objects / headers and any CMake we choose (currently nothing special) into a CMake project that makes use of libjpeg-turbo. It is included by the `libjpeg-turboConfig.cmake` file.

> What function the libjpeg-turboConfigVersion.cmake file serves

This part is optional according to the [CMake Packages spec](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html?highlight=packages) but it is pretty standard. It allows us to use CMake commands like `find_package(libjpeg-turbo 2.0.2 CONFIG)` which will not succeed if the version we asked for is not compatible with the version installed.

> My preference, if possible, would be to have one file named libjpeg-turbo-config.cmake (not libjpeg-turboConfig.cmake) that is installed under ${CMAKE_INSTALL_LIBDIR}/cmake (not ${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}), but if there is a good reason why that isn't a good idea, then please let me know.

A file ending `-config` is allowed according to the docs. `Given the name Foo, it looks for a file called FooConfig.cmake or foo-config.cmake`. The default search paths are given in the [find_package docs](https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure) and other folders are permitted. I have only seen this `${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}` used in other projects though (I don't really know the implications of moving it). The reason why it is multiple files, and therefore in a folder names libjpeg-turbo, is due to how they are generated by CMake. Also the `-release` and `-debug` configs will be installed to the same folder by two different CMake invocations.

**Comment by dcommander** [comment]
I'd be curious to know how, or if, other open source libraries are dealing with this issue.  Is there another library as common as libjpeg-turbo that is also shipping CMake config files?  I'd feel more comfortable with this if I could verify that it produces similar config files to those produced by other popular projects.

**Comment by hjmallon** [comment]
I believe OpenCV and Qt both produce CMake `*Config.cmake` files. Not sure what the proportion of large/popular libraries is.

**Comment by Youw** [comment]
> Is there another library as common as libjpeg-turbo that is also shipping CMake config files?

Check OpenCV Windows build, e.g.:
https://sourceforge.net/projects/opencvlibrary/files/4.2.0/opencv-4.2.0-vc14_vc15.exe/download

It is a good example (can't say the best implementation I've seen, but it does work) of a large CMake package with multiple builds/configs supported at once.

**Comment by kolibri91** [comment]
Is this PR still active, I would be interest in the results of it?

**Comment by dcommander** [comment]
Yes, it is still active.  I intend to implement this feature in libjpeg-turbo 2.1 but have not had a chance to do so yet.  COVID-19 created a sudden demand for my remote display software (VirtualGL and TurboVNC), so I had to spend a few months fixing unexpected bugs.  Thus, libjpeg-turbo 2.1, which I intended to release this summer, is a few months behind schedule.

**Comment by kolibri91** [comment]
I verified if I can build you PR (I have quite the same patch as @hjmallon for v2.0.4 and was looking if I should report it to upstream).
To make it short, I'm still not able to build the package without one additional change:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 14891a2..a45d292 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -107,7 +107,7 @@ if(CMAKE_INSTALL_PREFIX STREQUAL "${CMAKE_INSTALL_DEFAULT_PREFIX}")
   endif()
 endif()

-include(cmakescripts/GNUInstallDirs.cmake)
+include(GNUInstallDirs)

 macro(report_directory var)
   if(CMAKE_INSTALL_${var} STREQUAL CMAKE_INSTALL_FULL_${var})
--
```

When I not apply this change, I get absolute paths in the `INTERFACE_INCLUDE_DIRECTORIES` which leads cmake to fail.
Can you please give me a hint what I'm doing wrong?

**Comment by dcommander** [comment]
I am trying to eat my own dog food and use the libjpeg-turbo CMake package config file in a downstream project, but it doesn't appear to work.  `find_package()` finds the official libjpeg-turbo package with no problem as long as I set `CMAKE_PREFIX_PATH` to **/opt/libjpeg-turbo**, and the targets are successfully imported.  However, any attempt to link with the imported targets, even in the same directory scope, fails.  What am I doing wrong?

**Comment by kolibri91** [comment]
@dcommander 

Could you might share more infomation with us? 
Which linker do you use?
What is your error message?

**Comment by dcommander** [comment]
Actually it seems to work in isolation, so it must be something specific in my build system.  I will do more research.

**Comment by dcommander** [comment]
Well, it all works now.  I guess I mistyped something.

**Comment by Youw** [comment]
> I set `CMAKE_PREFIX_PATH` to /opt/libjpeg-turbo

This is probably not related to the issue you had, but a general recommendation from a CMake user: set `libjpeg-turbo_ROOT` to  `/opt/libjpeg-turbo` instead of touching `CMAKE_PREFIX_PATH` at all. That's the best way of specifying external dependencies if the path contains (and supposed to contain) only a single package/library.

**Pull request closed without merging**
