### PR TITLE
Build: Add CMake options INSTALL_UTILS and INSTALL_DOCS

### PR DESCRIPTION
**Pull request by hjmallon**
* Allow disabling utils installation and docs installation

### CODE REVIEW

**Comment by dcommander** [comment]
Duplicate of #265.  Please see comments on that PR.  I will accept a solution that uses the `COMPONENT` feature of `install()` but not something that introduces additional cruft into the build system.

**Comment by hjmallon** [comment]
As far as I see there are a few specific ways that we could implement this. I wonder if any of these methods would be suitable?

1. COMPONENT install and make install_libs/install_utils type targets

Would require adding COMPONENT values to all install() commands in CMake and and add_custom_target for each install_X target that would be useful (the only one I would use would be install_libs or similar).

Downsides: make install_libs cannot be made to depend on ALL_BUILD so user would have to do make all first.

2. COMPONENT install and have a cmake variable where you can set which COMPONENT is installed with make install.

Would require adding COMPONENT values to all install() commands in CMake and and a bit of install(CODE) for setting the default COMPONENT. Also a small patch for the cmake_uninstall script.

Downsides: Adds new cmake var. Must rerun cmake to install each COMPONENT (only an issue for installing 2 or more)

3. OPTIONAL 

install(X OPTIONAL) allows us to not fail if the source file is not available. This can only be expanded into choosing parts to install if the build system provides options over whether targets are built first. It would not allow any options over the docs (which are always available).

**Comment by hjmallon** [comment]
I think maybe this change should set downstream of here. Thanks for your time.

**Comment by dcommander** [comment]
I am happy to add `COMPONENT` to all `install()` commands.  You would then be able to invoke `cmake_install.cmake` directly, as described in https://github.com/libjpeg-turbo/libjpeg-turbo/pull/333#issuecomment-467153355.  The only downside is that you may have to invoke it separately for each component you need to install, e.g.:

```
cmake -DCOMPONENT=lib -P cmake_install.cmake
cmake -DCOMPONENT=doc -P cmake_install.cmake
```

If you chose to build additional downstream functionality upon that, such as an `install_libs`/`install_utils` target, then at least you'd have fewer modifications to maintain.

**Pull request closed without merging**
