### PR TITLE
Android NDK build Instructions

### PR DESCRIPTION
**Pull request by fanzhengchen**
I try to follow original instructions to compile the libjpeg-turbo souce code with ndk 16.1.4479499, but I encounter some errors such as "C processor  arm-linux-android-gcc sanity check failed", "undefined referenced to stderr". So I modify the script to generate the standalone script the generate the ndk build toolchains and remove the sysroot variable. I manage to compile the source code after that, I have added the script which I have already successfully compiled the project in BUILDING.md. Please check out that.

### CODE REVIEW

**Comment by dcommander** [comment]
Please figure out why the procedure in BUILDING.md is failing (it works fine for me), then we can modify that procedure accordingly, but canonizing hacks and workarounds is never a good idea.

**Comment by dcommander** [comment]
Also,

"Building libjpeg-turbo for Android platforms requires the specific needs.  Android NDK and autotools."

is not proper English and is minimally confusing if not outright nonsensical.

**Comment by fanzhengchen** [comment]
I follow the original document and have the script as follow
```shell
#!/bin/sh

NDK_PATH=$NDK

BUILD_PLATFORM="linux-x86_64"
TOOLCHAIN_VERSION=4.9
ANDROID_VERSION=16
HOST=arm-linux-androideabi
SYSROOT=${NDK_PATH}/platforms/android-${ANDROID_VERSION}/arch-arm
ANDROID_CFLAGS="-march=armv7-a -mfloat-abi=softfp -fprefetch-loop-arrays \
  --sysroot=${SYSROOT}"

TOOLCHAIN=${NDK_PATH}/toolchains/${HOST}-${TOOLCHAIN_VERSION}/prebuilt/${BUILD_PLATFORM}

echo $TOOLCHAIN

export CPP=${TOOLCHAIN}/bin/${HOST}-cpp
export AR=${TOOLCHAIN}/bin/${HOST}-ar
export NM=${TOOLCHAIN}/bin/${HOST}-nm
export CC=${TOOLCHAIN}/bin/${HOST}-gcc
export LD=${TOOLCHAIN}/bin/${HOST}-ld
export RANLIB=${TOOLCHAIN}/bin/${HOST}-ranlib
export OBJDUMP=${TOOLCHAIN}/bin/${HOST}-objdump
export STRIP=${TOOLCHAIN}/bin/${HOST}-strip
sh ./configure --host=${HOST} \
  CFLAGS="${ANDROID_CFLAGS} -O3 -fPIE" \
  CPPFLAGS="${ANDROID_CFLAGS}" \
  LDFLAGS="${ANDROID_CFLAGS} -pie" --with-simd ${1+"$@"}
make
```
result in 
```shell
configure: error: C preprocessor "/home/mark/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-cpp" fails sanity check
```
Besides the fprintf function has reference the macro stderr which is commented in NDK <stdio.h> right now, we have to add  -D__ANDROID_API__=$API_LEVEL to the cflags. Otherwise we have to modify the source to complete the compilation.
I think if we try to use NDK to compile the cpp project by configure file, the standalone toolchians is a better idea which is referenced by [Android Developer](https://developer.android.com/ndk/guides/standalone_toolchain.html)

**Comment by dcommander** [comment]
This problem is due to a regression in the NDK distribution.  The version I use works fine with the procedure in BUILDING.md.  The newest version experiences the issue you are reporting, because the sysroot (`${NDK_PATH}/platforms/android-${ANDROID_VERSION}/arch-arm`) no longer contains a usr/include directory.  I will investigate how to modify the documentation accordingly, but I am not going to include your script as-is.

**Comment by dcommander** [comment]
FYI, the instructions in BUILDING.md work fine with NDK r15c, so this regression was introduced in NDK r16.

**Comment by dcommander** [comment]
Modified the build instructions to accommodate NDK r16b while preserving backward compatibility with previous NDK releases.  I will revisit this issue in libjpeg-turbo 1.6, since we really need to transition to the Clang-based NDK toolchain anyhow, but for libjpeg-turbo 1.5.x, I want to change as little as possible.

**Comment by dcommander** [comment]
I have merged the new build instructions into dev, but for now, I'm sticking with the GCC-based toolchain until I have a chance to test the Clang-based toolchain for performance and device compatibility.  The Clang-based toolchain also has backward compatibility issues.  Specifically:

* It requires glibc 2.14 or later, so it is incompatible with some of the build platforms (notably: RHEL 6) that we still have to support.
* It can't be made to work without using make_standalone_toolchain.py/make-standalone-toolchain.sh.
* The version of Python that is required by make_standalone_toolchain.py is also not compatible with older-but-still-supported build platforms.

So the longer I can delay introducing those backward compatibility issues, the less likely they are to affect users.  But the main thing is that I need to dig out my Android test devices and make sure that a Clang build doesn't regress in terms of performance or compatibility.  I'm also waiting to see whether Google restructures the NDK yet again in a future release.

Marking as Revisit, and I will revisit the issue prior to the beta release to see where the NDK stands at that point in time.

**Pull request closed without merging**
