### PR TITLE
Some potentially useful PVS-Studio fixes

### PR DESCRIPTION
**Pull request by dimhotepus**
PVS-Studio static analyzer found some suspicious places. 

Could you please, take a look?

P.S. Huge thanks for `libjpeg-turbo` enhancements and support!

Product page: https://www.viva64.com/en/pvs-studio/
How to use for free (almost): https://www.viva64.com/en/b/0600/

### CODE REVIEW

**Comment by dcommander** [comment]
These issues are all pedantic, and realistically, it doesn't make sense to do a one-time fix of pedantic issues unless it is in the context of adopting an easily-reproducible QC workflow.  As an example, I enable a plethora of strict GCC warnings in my local libjpeg-turbo builds, so if any of these issues could be reproduced with one of those warnings, then that would be the most straightforward way to ensure that the issue is fixed and remains fixed.  If the only way to detect such issues is with proprietary tools, then there would be a high likelihood that similar issues would be introduced in the future, since I don't have the time to constantly run PVS-Studio against the code base.

**Comment by dimhotepus** [comment]
> These issues are all pedantic, and realistically, it doesn't make sense to do a one-time fix of pedantic issues unless it is in the context of adopting an easily-reproducible QC workflow. As an example, I enable a plethora of strict GCC warnings in my local libjpeg-turbo builds, so if any of these issues could be reproduced with one of those warnings, then that would be the most straightforward way to ensure that the issue is fixed and remains fixed. If the only way to detect such issues is with proprietary tools, then there would be a high likelihood that similar issues would be introduced in the future, since I don't have the time to constantly run PVS-Studio against the code base.

In general I agree with you. These issues are mostly pedantic and it is possible that same ones are introduced later.

What I can suggest is running free PVS-Studio version in CI like this: https://pvs-studio.com/en/blog/posts/0457/ (TLDR add special comment to *.c files) + acquiring free license from them.

Anyway, does it makes sense to fix at least these issues, because we already know they are present?
Ex. https://github.com/libjpeg-turbo/libjpeg-turbo/pull/571/commits/26b01b8486e088f1a7727a66dd6a0edb3b83e768, https://github.com/libjpeg-turbo/libjpeg-turbo/pull/571/commits/e2b539a9e057a7c8ebf15560db93a62081c4a678 looks useful for me.

**Comment by dcommander** [comment]
I agree that 26b01b8 fixes a legitimate API issue, and I have committed that fix to all relevant branches.  The issue fixed by e2b539a, however, actually is pedantic, although I admit that the reason why isn't obvious from reading the code.  `tjDecompress*()`, `tjDecompressToYUV*()`, and `tjTransform()` all set the value of `dinfo->progress` to `NULL` if `TJFLAG_LIMITSCANS` is not specified.  Since the `jpeg_decompress_struct` pointer (`dinfo`) is opaque to the TurboJPEG caller, we only have to worry about other TurboJPEG functions that might access that pointer.  Those functions are `tjDecodeYUV*()` and `tjDecompressHeader*()`, none of which call any of the underlying libjpeg API functions (`jpeg_read_scanlines()`, `jpeg_read_raw_data()`, `jpeg_start_decompress()`, and `jpeg_start_output()`) that would potentially refer to `dinfo->progress`.  Anyhow, the proposed TurboJPEG v3 API overhaul (#517) will render that issue irrelevant, since the TurboJPEG API flags will be replaced by state setting functions.  Thus, the progress monitor will become part of the structure referred to by the TurboJPEG instance handle.  I will investigate whether additional pedantic GCC warnings might catch some of the other issues.

I have no interest in incorporating a proprietary tool into our CI process, because that violates the principle of reproducibility.  With the exception of the GPG private key used to sign our pre-release packages and the AWS credentials used to upload them, anyone could fork libjpeg-turbo and produce their own CI builds from their fork, but they couldn't do that if the CI build process depended on a proprietary software license issued only to me.

**Comment by dcommander** [comment]
Final status:

https://github.com/libjpeg-turbo/libjpeg-turbo/pull/571/commits/b93a5a169342a745fd02cef7135f5d8ea50a4024 and https://github.com/libjpeg-turbo/libjpeg-turbo/pull/571/commits/27d2a1dac2af8630b6a7afe8d38609c5f8cb114d: Integrated in 1f55ae7b0fa3acc348a630171617d0e56d922b68, which fixes those and other compiler warnings uncovered with `-Wpedantic`.

https://github.com/libjpeg-turbo/libjpeg-turbo/pull/571/commits/7e5e19e5d198712715f4c2b8eba70b9ef5723773 and https://github.com/libjpeg-turbo/libjpeg-turbo/pull/571/commits/2e944ca645b1678ffb7628893fb723a4a8cbe665: Rejected as irrelevant, since those macros are only used internally and are never passed an expression as the first argument.

https://github.com/libjpeg-turbo/libjpeg-turbo/pull/571/commits/4be6d4e7bdd09a73ee8456aa07693afa31ef2148: Rejected as incorrect (`quiet` can actually be 2, so the code is correct as written.)

https://github.com/libjpeg-turbo/libjpeg-turbo/pull/571/commits/26b01b8486e088f1a7727a66dd6a0edb3b83e768: Integrated in a7f0244e9bf31233918388cc0321e01ccc07ba5c.

https://github.com/libjpeg-turbo/libjpeg-turbo/pull/571/commits/e2b539a9e057a7c8ebf15560db93a62081c4a678: Rejected as irrelevant for reasons described above.

**Comment by ValZapod** [comment]
> Rejected as incorrect (`quiet` can actually be 2, so the code is correct as written.)

Actually your first check for true then for false and that is all, all values are done, so last else is impossible. Obviously your fix is very wrong, since there are now two bare else.

**Comment by dcommander** [comment]
@ValZapod You're right.  Apparently that was introduced accidentally in 890f1e0413b54c40b663208779d4ea9dae20eaef, although it is innocuous.

**Pull request closed without merging**
