### PR TITLE
Fix md5cmp for AmigaOS4 PPC-BE

### PR DESCRIPTION
**Pull request by chris-y**
md5cmp wasn't working on OS4 because md5.c assumed that BYTE_ORDER and/or LITTLE_ENDIAN had been defined.  When none of them were defined, it thought the CPU was little endian, and the MD5 results were wrong as a consequence.

I've added the machine/endian.h header which defines BYTE_ORDER and had to add a BSD endian.h as we don't have htole32() and friends here (I think this is OK given the licence in the file)

It might not be necessary to enclose all those includes in the #ifdef but I didn't want to inadvertently break anything else (machine/endian.h would definitely be better off being included for everyone if possible, as otherwise the BYTE_ORDER==LITTLE_ENDIAN comparison is pointless)

### CODE REVIEW

**Comment by chris-y** [comment]
Apologies for the extraneous commits there, the pull req log showed the correct changes without any extras despite that.  I get tangled in knots with git sometimes.

**Comment by dcommander** [comment]
Unfortunately the 4-clause BSD license in endian.h would complicate things, because libjpeg-turbo uses a 3-clause BSD license for any non-libjpeg-derived code.  Does AmigaOS even support little endian?  If not, then it seems like you could just hard-code the appropriate macros within your #ifdef.

**Comment by chris-y** [comment]
It doesn't support little endian, so that's probably a saner solution.  I'll have a re-think.

**Comment by dcommander** [comment]
Any further updates on this?

**Comment by chris-y** [comment]
My apologies, I got distracted and forgot.  I've just pushed an update which does the byte-swapping within md5.c.
All the tests pass with this version of md5cmp.

**Comment by dcommander** [comment]
Sorry, this time I do need you to squash all of this down into a single commit against master, and please convert tabs to spaces.  Also, are the includes (endian.h and stdint.h) still necessary?

**Comment by chris-y** [comment]
machine/endian.h is, as otherwise the rest of the file thinks it's little endian. I think this ought to be included for everything if possible - I've not tried building on Linux PPC-BE but suspect it won't work there either without this include (but I also don't know for sure if that include is available).
stdint.h isn't needed, I've removed.
Do I need to re-submit the pull request?

**Comment by dcommander** [comment]
I don't see the changes yet.  Did you push them?  Once you do that, I can figure out whether I can merge it as-is or whether I need a new PR.

**Comment by chris-y** [comment]
Yes, pushed.

**Comment by dcommander** [comment]
Not sure why it wasn't showing me the latest commit, but I cloned your fork and created a new commit from that (I needed to add the feature to the change log anyhow.)

You'll probably want to also try building from the dev branch, since it now uses CMake.  Not sure whether CMake is available on AmigaOS or not.  You'll have to cherry pick this new commit into dev, because I generally don't merge from master into dev until I have 3 or 4 new commits in master, or until I'm about to start working on something in dev.  Hopefully the new build system will "just work" on AmigaOS, but if not, please open a new issue describing how it fails.

**Comment by chris-y** [comment]
CMake isn't available (there's an old port, but I never had any luck with it).  I'm cross-compiling it anyway.

**Pull request merged**
