### PR TITLE
Use builtin CMake module GNUInstallDirs instead of the local copy.

### PR DESCRIPTION
**Pull request by Lastique**
This fixes LIBDIR path composition with CMake 3.13.2. The local copy would append the absolute LIBDIR to the PREFIX path instead of using the relative path, if CMAKE_INSTALL_LIBDIR is specified by user.

Since this change requires GNUInstallDirs to be part of CMake distribution, bumped minimum CMake version to 3.0.2 (the oldest one that has documentation for this module).

### CODE REVIEW

**Comment by Lastique** [comment]
I'm attaching the build log with the error that is solved by this PR: 
[libjpeg-turbo.log.gz](https://github.com/libjpeg-turbo/libjpeg-turbo/files/2825018/libjpeg-turbo.log.gz)

In the log, you can see in the end that the libraries are installed into `/build/libjpeg-turbo/libjpeg-turbo/debian/tmp/build/libjpeg-turbo/libjpeg-turbo/.tmp/lib/x86_64-linux-gnu`. This path mistakenly includes `/build/libjpeg-turbo/libjpeg-turbo/.tmp` part, which is the full path to the build directory, and you can also see it is prepended by CMake to `CMAKE_INSTALL_LIBDIR` in the beginning of the log.

**Comment by Lastique** [comment]
You are free to not merge this PR if it is not acceptable, of course. I'm fine with that. In that case, consider this a problem report.

**Comment by dcommander** [comment]
It works fine if the build instructions are followed:
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/BUILDING.md#installing-libjpeg-turbo

"
NOTE: If setting one of these directory variables to a relative path using the CMake command line, you must specify that the variable is of type `PATH`. For example:

```
cmake -G"{generator type}" -DCMAKE_INSTALL_LIBDIR:PATH=lib {source_directory}
```

Otherwise, CMake will assume that the path is relative to the build directory rather than the install directory.
"

This requirement doesn't exist in CMake's distribution of GNUInstallDirs.cmake, but a lot of other features that our build system needs also don't exist in CMake's distribution of GNUInstallDirs.cmake.  I refer you to the Git log for that file for a complete description of the features I added to it and why.

**Comment by dcommander** [comment]
Also, your issue description above implied that this issue only occurred with CMake 3.13.x.  It occurs with any release of CMake.  Your proposed patch in fact breaks the build if `WITH_JAVA` is enabled (one of the many reasons why we use our own version of GnuInstallDirs.)

**Comment by Lastique** [comment]
Ok, thank you.

**Comment by dcommander** [comment]
Because of 5a2353c2dad951af3f823ca4f9bdee293876cea1, it should now be possible to specify relative paths in the various `CMAKE_INSTALL_*DIR` variables without prefixing the values with `:PATH=`.

**Pull request closed without merging**
