### PR TITLE
Enable CMake project for platforms other than Windows.

### PR DESCRIPTION
**Pull request by marsupial**
Tested on Linux-64 and OS X.
Unclear if the changes in the second commit could be handled in CMake, but it seems incorrect either way,

### CODE REVIEW

**Comment by dcommander** [comment]
Already implemented in dev, and has been for quite some time.

**Comment by marsupial** [comment]
It does beg the question why it is not in master...

**Comment by dcommander** [comment]
master is always stable.  dev will be merged into master when libjpeg-turbo 1.6 beta is ready for release.  At the moment, it is not yet feature-complete.

**Comment by dcommander** [comment]
More details here:
http://www.libjpeg-turbo.org/DeveloperInfo/CodeAccess

libjpeg-turbo used to use a TBD (trunk-based development) branch model, in which the latest code was always in the master branch ("trunk" in the SVN days) but I moved away from that branch model upon migrating to GitHub.  The stable mainline branch model seems to be the preferred model among open source projects these days.  One reason is that Git merges don't work properly with TBD, since it requires cherry picking commits from master into the stable branch(es).

**Comment by dcommander** [comment]
Even more details here:
https://github.com/libjpeg-turbo/libjpeg-turbo/issues/56

**Pull request closed without merging**
