### PR TITLE
Build: Use GNUInstallDirs for standard path defaults

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
The build currently uses its own variables (`BINDIR`, `DATADIR`, `DOCDIR`, `INCLUDEDIR`, `LIBDIR`, `MANDIR`) and defaults for these paths, as well as its own defaults for `CMAKE_INSTALL_PREFIX`.

This commit makes the build use the CMake [GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) module for these variables.  This module matches the behaviour of the GNU Coding Standards as implemented by Autoconf and Automake by default, as well as accounting for several Linux Filesystem Hierarchy Standard (FHS) behaviours and Debian/Ubuntu multiarch library directory naming.

This change will:

- Make the behaviour closer to the expectations of users of the old Autotools build
- Replace custom variables with standard variables which are expected by CMake users
- Provide defaults similar to the old Autotools build
- Provide defaults expected by CMake users for both the install prefix and the various installation directories
- Integrate seamlessly into projects building multiple CMake-based projects which are already using the standard variable naming conventions and defaults

I have provided a compatibility mapping from the old variables to the GNUInstallDirs variables to provide a clean transition.  I also quoted the variables to cope with spaces in paths explicitly.

--------

Testing:

- Both the old and new option names will continue to work; using the old option names will elicit a warning
- All uses of the old variable names should have been converted
- The logic in the rpm and dpkg scripts might need checking in case there's some subtlety I overlooked

### CODE REVIEW

**Comment by dcommander** [comment]
I'm going to need to re-implement this, because you ripped out some intentional code and some of the build documentation, and several other things are broken.  Stand by.

**Comment by rleigh-codelibre** [comment]
I'm happy to revise it if you let me know what was ripped out that's required.  The docs changes match the code changes, so that's the reason why they were altered.

**Comment by dcommander** [comment]
OK, I see what happened.  You changed the default install prefixes.  There's a specific reason why I need those to be what they are.

**Comment by rleigh-codelibre** [comment]
Yes, this resets it to use the CMake defaults because the defaults hardcoded here are:

- not what a CMake user would expect
- not what an autotools user would expect
- will break builds relying on the defaults not being changed
- hardcode system-specific paths which may not be writable or even present

If I'm building a set of CMake-using packages, I would expect the behaviour to be the same, and not changed arbitrarily in each package.  One of the benefits of CMake packages is that consistency.  It should not be necessary to override the defaults.

If these paths are needed by a specific system, I would suggest that the general-purpose CMakeLists.txt is not the place for them. Could they could be placed into a support script which explicitly sets the appropriate prefix depending upon the system?  For example, [these scripts] are the Unix and Windows shell script and batch file used to run CMake builds on several different platforms on our CI infrastructure; we don't put the system-specific information into the general-purpose build scripts; we pass it in as cmake options.

**Comment by dcommander** [comment]
libjpeg-turbo has always used those default install paths, even with the autotools build system, so in fact changing them would represent a regression.  Those install paths are a product of our project's history.  When the project was first created, all Linux/Unix distributions were using libjpeg, so my goal was to provide an SDK that could co-exist with the system's installation of libjpeg.  That is still a goal, because not all O/S distributions supply the latest & greatest version of libjpeg-turbo.  Some of them also do not include the TurboJPEG API library or the Java classes, so it is necessary for developers to use our "official" SDK in many cases-- particularly when building non-OSS code.  Bear in mind that I work primarily in the high-end visualization industry, so it is often the case that software projects (including my other projects, which pay at least some of the bills for this project, although unfortunately not enough of them) expect libraries to be installed in a specific location.  This is particularly important in the case of the Java classes, because those classes interface with libturbojpeg using JNI, so they have to know where they can find libturbojpeg.so.  Also, your statements regarding expectations may be valid for Un\*x, but there is no real expectation among Windows users, and installing to a directory under c:\ is a common practice for Windows open source components.

My goal has never been to make libjpeg-turbo conform to any kind of GNU standard, because I never originally intended for it to be a system library.  I am proud of the fact that it is now being distributed far and wide and helping a lot of people, but at the same time, it doesn't make sense for me to spend my time conforming to a standard that I don't necessarily even agree with.  Personally, I think the pseudo-standard of installing 3rd-party software to /usr/local is outdated, and I've never liked doing that anyway, because it makes it difficult to tell which files belong to which software package.  The practice of installing under /opt is partly a relic of my previous work at Sun Microsystems, because on Solaris, all non-O/S packages are required to install their files under /opt/{package_name}.  I personally like that approach, because if you install libjpeg-turbo using our build system, then removing it is a simple matter of removing a single directory.  The default install paths are well documented and well understood by libjpeg-turbo developers, and as you can observe, the build system disables that behavior and uses the more GNU-friendly behavior if you change the install prefix to anything other than the default.  Thus, making the build system conform to the GNU standard is a simple matter of passing `-DCMAKE_INSTALL_PREFIX=/usr/local` to CMake.

I don't have a problem with using the GNUInstallDirs extension instead of our custom install directories, but I am not willing to change the default install paths.

**Comment by rleigh-codelibre** [comment]
I can certainly revert that part of the pull request (pushed).  I just wanted to point out that the defaults are not optimal in the context of wider integration, though they may well make sense within the historical context of this specific project.

**Comment by dcommander** [comment]
I understand the issues, but everyone who is currently integrating libjpeg-turbo is already having to deal with that.  Thanks for the PR.  I'll try to get this integrated within the next day or so.

**Comment by dcommander** [comment]
I looked at the GNUInstallDirs stuff briefly, and unfortunately it's not going to be as simple as I had hoped.  If you set any of the `CMAKE_INSTALL_*DIR` options from the command line, then those options cease to be visible in the cache, and thus they can't be modified with ccmake or cmake-gui.  Not cool.  About the only thing that GNUInstallDirs does better than our system is setting the library directory.  I'm going to have to look at this more closely to figure out how to make it do what I want.

**Comment by rleigh-codelibre** [comment]
@dcommander This depends upon how you set them on the command line.  CMake cache options are typed, and if you just do e.g. `-DCMAKE_INSTALL_BIN_DIR=foo` it will have an INTERNAL type which is hidden (it's cached, but not presented in the GUI).  The correct way to set it is to use `-DCMAKE_INSTALL_BIN_DIR:PATH=foo` and then it will show up as expected.

**Comment by dcommander** [comment]
Except that that is non-intuitive, which defeats the purpose of switching to this system (this move is supposed to make the specification of install directories more intuitive, not less), and also, when you specify the variable in that manner, the cache entry has no help string.  This is going to require an ugly hack, unfortunately.

**Comment by rleigh-codelibre** [comment]
It isn't as intuitive as I'd like, but it *is* the standard cmake behaviour for cache variables, which every other package using this facility uses.  The GNUInstallDirs macro does add these to the cache by default.  It looks like it doesn't forcibly add them when you specify them by hand, but that's because they were added by the user.  If the user doesn't specify the type, they don't appear in the GUI.  As a package using cmake, that's not really our problem--that's simply the way the cmake tool works.  If the user wants to use the GUI after running cmake, and wants to change the option, then they need to specify the PATH type.  This is a very rare circumstance; most users either (1) specify it on the command line or (2) use the GUI.  Needing to do both is rare.

**Comment by rleigh-codelibre** [comment]
FYI: [github branch](https://github.com/Kitware/CMake/compare/master...rleigh-codelibre:installdir-cache-type?expand=1) and [gitlab merge request](https://gitlab.kitware.com/cmake/cmake/merge_requests/313) to improve the default behaviour in cmake itself.

**Comment by dcommander** [comment]
At the moment, it doesn't seem possible to make you happy while making myself happy at the same time.  The only ways forward I see for this are:

1. Including a local copy of GNUInstallDirs and modifying it to suit my needs.  That would include the following mods:
    * The ability to change the default values for specific `CMAKE_INSTALL_*DIR` variables
    * Improved variable documentation (I understand that you basically just cribbed the documentation from autotools, but one of the goals of this new build system was to get away from annoying autotools behaviors.)
    * Keeping variables in the cache even if they are set prior to invoking GNUInstallDirs.  I disagree that the current behavior of GNUInstallDirs in this regard is in any way normal.  If, for instance, I set `CMAKE_C_FLAGS` from the command line, then it still appears in the cache.  That is what I expect as a user of CMake.
    * Eliminating some confusing cache behavior, such as the fact that `CMAKE_INSTALL_DOCDIR` and `CMAKE_INSTALL_MANDIR` appear blank in the cache despite the fact that their contents are actually dependent on `CMAKE_INSTALL_DATAROOTDIR`.  Frankly, for our purposes, the distinction between `CMAKE_INSTALL_DATADIR` and `CMAKE_INSTALL_DATAROOTDIR` is irrelevant, so I don't find it particularly necessary to adopt that aspect of the GNU pseudo-standard.

    I would additionally clear the advanced flag on the variables we actually use, but that's a personal preference, and it can be accomplished in our project's CMakeLists.txt file.

    Including a local copy of GNUInstallDirs is the only option here, since we cannot require the latest & greatest CMake version (some O/S distributions that need to absorb this new build system will still be stuck on older versions of CMake.)

... or ...

2. Continue to use our existing system, with perhaps some improvements such as:
    * Prefixing our variable names with `CMAKE_INSTALL_` in order to more closely emulate the GNUInstallDirs system
    * Allowing relative directory names

Frankly, I didn't have time to create this build system in the first place, and I certainly don't have time to spend on improving the GNUInstallDirs module, so my inclination at the moment is to go for (2).  GNUInstallDirs is an overkill in some ways and an underkill in others, and I don't think any of my modifications to it would be acceptable to you anyhow due to our philosophical differences.  I don't really see that the GNUInstallDirs module provides many advantages over our existing system.  It includes a lot of functionality that I don't need (which means that maintaining a fork of it would be more trouble than it's worth.)  I can implement relative pathnames more straightforwardly using our existing system.  The only other advantage of GNUInstallDirs is that it can set more intelligent, platform-specific defaults for `*LIBDIR`, but the old autotools system couldn't do that, so the fact that our new system sets `*LIBDIR` to `${CMAKE_INSTALL_PREFIX}/lib` (unless you're doing an official build) is not a regression.

**Comment by dcommander** [comment]
You can read my lengthy commit message above for the details of what I did.  I decided to go with Option 1 after all (using a local copy of GNUInstallDirs.)  This took considerable effort (15-20 hours of additional unpaid work.)  It was necessary to rewrite most of the GNUInstallDirs module to support the features I needed and to make it behave like I would expect.  In doing so, I significantly cleaned up the existing LIBDIR implementation.  I needed to do basically the same thing for all of the variables (make it such that they will automatically switch values if `CMAKE_INSTALL_PREFIX` changes and the variable was never set by the user.)  Once I implemented a second set of variables that allowed the defaults to be overridden, then it was straightforward to make the variables always reside in the cache, regardless of how they were set.  Once I made the variables always reside in the cache, it was straightforward to make them track changes to `CMAKE_INSTALL_PREFIX`.  I also added a variable for Java classes and made other enhancements and fixes described in the commit message.  A lot of the time was spent regression testing to ensure that the packaging system still worked properly (your PR broke it, because you weren't using the full pathname variables in the generated package scripts.)  I used pkgdiff to ensure that the generated SRPM, RPM, DEB, and tarball files were identical to the ones generated prior to the modification, and I tested all supported platforms to ensure that the behavior of the build system has not regressed.

Note that it was not necessary to keep the "old" variables (`*DIR`), because those were introduced with the cross-platform CMake build system, which is brand new and has not yet been officially released.

**Comment by dcommander** [comment]
Just pushed a new version that now allows any directory variable to refer to any other directory variable by enclosing the variable name in angle brackets.  The module then replaces these with `@` and processes the strings using `string(CONFIGURE ...)`.  Pretty cool stuff.

**Comment by dcommander** [comment]
One other thing I noticed-- not something that affects libjpeg-turbo, but something that I noticed as I was trying to integrate this module into TurboVNC.  If `CMAKE_INSTALL_SYSCONFDIR` is "etc" and `CMAKE_INSTALL_PREFIX` is "/opt/{something}", then `CMAKE_INSTALL_FULL_SYSCONFDIR` is rewritten to "/etc/opt/{something}".  That causes a mismatch, because if you pass `CMAKE_INSTALL_SYSCONFDIR` (which is still "etc") to CMake's `install()` command, it will install the files in "/opt/foo/etc".  However, that doesn't match the value of `CMAKE_INSTALL_FULL_SYSCONFDIR`.  I think it would be more correct to rewrite `CMAKE_INSTALL_SYSCONFDIR` with the absolute path in this case.

**Pull request closed without merging**
