### PR TITLE
Add `COMPONENT` to all `install()` commands

### PR DESCRIPTION
**Pull request by kleisauke**
Allows users to choose specific components for installation. The names of the components are based on the directory in which they will be installed.

Helps: https://github.com/libvips/libvips/pull/3931.
Context: https://github.com/libjpeg-turbo/libjpeg-turbo/pull/338#issuecomment-469359200.

### CODE REVIEW

**Comment by dcommander** [comment]
I am out of the office right now but will evaluate this when I get back.

**Comment by dcommander** [comment]
For some reason, installing the `runtime` component doesn't install the shared libraries.  I've tried that on two different systems running two completely different operating systems and CMake versions.  Any idea what's going on?

**Comment by kleisauke** [comment]
Ah, you're right. It looks like `COMPONENT` needs to be applied to each [`<artifact-kind> <artifact-option>...`](https://cmake.org/cmake/help/latest/command/install.html#signatures) group, fixed with commit e24359ebb3dbe5365031f6238cdd8168e2c040f2.

I now see:
```console
$ cmake -GNinja -DCMAKE_INSTALL_PREFIX=/tmp .
$ cmake --build .
$ cmake --install . --component runtime
-- Install configuration: "Release"
-- Installing: /tmp/lib64/libjpeg.so.62.4.0
-- Installing: /tmp/lib64/libjpeg.so.62
-- Set non-toolchain portion of runtime path of "/tmp/lib64/libjpeg.so.62.4.0" to "/tmp/lib64"
-- Installing: /tmp/lib64/libjpeg.so
-- Installing: /tmp/bin/cjpeg
-- Set non-toolchain portion of runtime path of "/tmp/bin/cjpeg" to "/tmp/lib64"
-- Installing: /tmp/bin/djpeg
-- Set non-toolchain portion of runtime path of "/tmp/bin/djpeg" to "/tmp/lib64"
-- Installing: /tmp/bin/jpegtran
-- Set non-toolchain portion of runtime path of "/tmp/bin/jpegtran" to "/tmp/lib64"
-- Installing: /tmp/lib64/libturbojpeg.so.0.3.0
-- Installing: /tmp/lib64/libturbojpeg.so.0
-- Set non-toolchain portion of runtime path of "/tmp/lib64/libturbojpeg.so.0.3.0" to "/tmp/lib64"
-- Installing: /tmp/lib64/libturbojpeg.so
-- Installing: /tmp/bin/tjbench
-- Set non-toolchain portion of runtime path of "/tmp/bin/tjbench" to "/tmp/lib64"
-- Installing: /tmp/bin/rdjpgcom
-- Set non-toolchain portion of runtime path of "/tmp/bin/rdjpgcom" to "/tmp/lib64"
-- Installing: /tmp/bin/wrjpgcom
-- Set non-toolchain portion of runtime path of "/tmp/bin/wrjpgcom" to "/tmp/lib64"
```

Thinking about this further, perhaps the `runtime`-tag is too broad? I could split it to `runtime-lib` and `runtime-exe`, which would let someone install the shared libraries _without_ the executables.

**Comment by kleisauke** [comment]
Good idea! I've updated the PR to incorporate this.

**Comment by dcommander** [comment]
Further thoughts:

It doesn't make much sense to install the executables without the shared libraries, because if libjpeg-turbo is built with `ENABLE_SHARED=1` (the default), then the executables will depend on the shared libraries.  It also probably doesn't make much sense to install the development libraries without the headers.  However, CMake doesn't do the "right thing" with respect to development stubs for Un*x shared libraries.  It treats both the shared library and its development stub as `LIBRARY` artifacts, so the ideal solution of placing the shared library into the `runtime` category and the development stub into the `devel` category isn't possible because of CMake's limitations.  The solution I like the most (or, rater, dislike the least) is the current solution of having a different component for every install directory.  I have integrated your latest patch with only a couple of minor formatting tweaks, as well as a modification to add a component for the Java JAR if using CMake 3.4 or later.

**Pull request closed without merging**
