### PR TITLE
Fix .pc files installation on MinGW

### PR DESCRIPTION
**Pull request by shinchiro**

### CODE REVIEW

**Comment by dcommander** [comment]
What is the purpose of this?  Installing the .pc files is innocuous if pkg-config isn't available.  As a matter of policy, we always install those files and have done so ever since they were added to the build.

**Comment by shinchiro** [comment]
The .pc files didn't install properly when cross-compile on mingw since it reside in `IF(UNIX)` bracket

**Comment by dcommander** [comment]
OK, well, then, the proper solution should be to change that to if(UNIX OR MINGW).  Trying to detect pkg-config at build time is inappropriate, because our build is not actually using pkg-config.

**Comment by dcommander** [comment]
Have you verified that the .pc files work under MinGW?  I don't think anyone has ever tested that.

**Comment by shinchiro** [comment]
Updated. I can confirm the .pc files is working well on MinGW platform

**Comment by dcommander** [comment]
Cygwin defines `UNIX`, so there should be no problem there.

**Pull request closed without merging**
