### PR TITLE
adding a Grayscale to YCbCr conversion .

### PR DESCRIPTION
**Pull request by ErwanMAS**
patch for master branch

### CODE REVIEW

**Comment by dcommander** [comment]
See my response under #255.

**Comment by ErwanMAS** [comment]
I understand that you don't want to patch 1.5x .

This patch give the ability to read a jpeg grayscale , and to generate a YCbCr  image .

Without this patch , the api stop reading with  JERR_CONVERSION_NOTIMPL .

**Comment by dcommander** [comment]
Why would you need to do that?  YCbCr is a JPEG colorspace, not an output colorspace.

**Comment by ErwanMAS** [comment]
my process do this :

**Comment by dcommander** [comment]
OK, but WHY do you need to generate a packed YCbCr image from a grayscale JPEG?  That is *not* a generic workflow.  "Generic" means "general case", and "general case" implies "common case."  I can think of no reason why someone would want to do what you're doing in a real-world application, since no common uncompressed image formats contain packed YCbCr pixels.

A YCbCr output colorspace has never been supported by any version of libjpeg or its derivatives.  If you want that to change, then you need to present a more convincing argument for why this modification is necessary.  You seem to be saying that libjpeg-turbo should convert from grayscale to YCbCr because it already converts from grayscale to RGB, but that's a bogus argument.  There is a *good reason* why grayscale-to-RGB conversion exists-- namely, because all of the common uncompressed file formats use some variant of RGB packed pixels.  There is no good reason why grayscale-to-YCbCr conversion should exist.

**Comment by ErwanMAS** [comment]
i never say that the process read only and only grayscale jpeg .

In my case this is a http image server . 
This process have access to many jpeg images in grayscale/color jpeg .
At the end This process  return a jpeg or a webp , with size alterations , cropping or color alterations .
The biggest advantage to keep a YCbCr image , is to speed up the re-encoding in jpeg .

**Comment by dcommander** [comment]
That makes no sense.  If your goal is to speed up re-encoding, then you would want to preserve the YCbCr or grayscale planar data, which the library is already able to do via `jpeg_read_raw_data()`/`tjDecompressToYUVPlanes()`.  By converting grayscale data to packed YCbCr, you are wasting CPU cycles and memory to perform that conversion (because the Cb and Cr components are wholly unnecessary in the output image), and you are further wasting CPU cycles to convert back to JPEG.  Just extract the grayscale data as-is and re-compress it to a grayscale JPEG image.

Sorry, but I remain unconvinced.  I cannot divine any purpose for this feature other than to support poor application design and abuse of the JPEG image format.  Unless you have anything further to add, this matter is closed.

**Pull request closed without merging**
