### PR TITLE
Handle CMake Policy CMP0048

### PR DESCRIPTION
**Pull request by foohyfooh**
Change where the project function call happens so the correct project logic is used, and so that the PROJECT_VERSION variable can be set using project function in CMake version 3.0 and higher.

### CODE REVIEW

**Comment by dcommander** [comment]
What is the benefit of this?  Why would someone need to set the `PROJECT_VERSION` variable?

**Comment by foohyfooh** [comment]
Sorry that I didn't make it clear the problem that this resolves.
Below is the issue that arises when working with your library with CMake 3.14.5

CMake Warning (dev) at /home/jonathan/image_project/third_party/libjpeg-turbo/src/CMakeLists.txt:7 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.  
The following variable(s) would be set to empty:
   PROJECT_VERSION
   PROJECT_VERSION_MAJOR
   PROJECT_VERSION_MINOR
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by dcommander** [comment]
I don't see that problem, and I'm building with a newer version of CMake than 3.14.5.  Are you trying to include libjpeg-turbo into your project without using CMake's `ExternalProject_Add()` function?

**Comment by foohyfooh** [comment]
I am using the function `add_subdirectory()` to include the dependency.

**Comment by dcommander** [comment]
That is explicitly not supported
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/.github/CONTRIBUTING.md

The job of the libjpeg-turbo build system is to build libjpeg-turbo.  It is unreasonable to expect our build system to support every possible downstream integration scenario.  Most of those scenarios would never be tested upstream, so even if I modified the upstream build system to support them, the chances of future breakage would be high.  If this enhancement fixed something that occurred during the course of building libjpeg-turbo as a standalone project, then I'd be happy to integrate it.  As it stands, the enhancement doesn't actually benefit our project.  It benefits your project, and thus, it needs to be integrated downstream.  `ExternalProject_Add()` is the only method we support for including libjpeg-turbo as a subdirectory of another project.  If anyone encounters issues with `ExternalProject_Add()` that could be remedied upstream, I'm happy to consider that, but if you choose to use `add_subdirectory()` instead, then it's your job to maintain any downstream build system modifications necessary to make that work.

**Comment by foohyfooh** [comment]
Did not notice the Contributing guide and the restriction with only supporting `ExternalProject_Add()`. Thank you for your time.

**Pull request closed without merging**
